### ISSUE TITLE
Possible to autoaccept update

### ISSUE THREAD

**Issue by paddymaster** [TS3Tools/TS3UpdateScript#104]
Hallo,

Ich hab heute mal dein Script ausprobiert.
Leider muss ich beim ausführen Yes eintippen. 

Welche Option wird denn benutzt für eine Autoaktieptanz?

**Comment by Sebi94nbg** [comment]
Hallo,
ein vollständig automatisches Update ohne jegliche Nachfrage ist nur mittels eines Cronjobs möglich.

Bei der manuellen Ausführung wird man immer gefragt. Mit einer entsprechenden Lizenz kannst du das Cronjob Feature für den vollständig automatisierten Update-Prozess nutzen. Alternativ kannst du das Skript selbst auf deine Bedürfnisse anpassen. Für die Anpassung gibt es jedoch keinen Support.

Siehe auch [Lizenzierung](https://github.com/TS3Tools/TS3UpdateScript#script-licenses). Mit der `Professional` Lizenz kann man das Skript vollständig automatisiert mittels Cronjob ausführen.
