### ISSUE TITLE
Wrong serveradmin password

### ISSUE THREAD

**Issue by polida** [TS3Tools/TS3UpdateScript#105]
About: This is the most widely used and fastest shell script to update all your TeamSpeak 3 server instances.
Author: Sebastian Kraetzig <info@ts3-tools.info> | Website: www.ts3-tools.info | facebook: www.facebook.com/TS3Tools
License: GNU GPLv3

 _____ ____ _____       _              _       _        __
|_   _/ ___|___ /      | |_ ___   ___ | |___  (_)_ __  / _| ___
  | | \___ \ |_ \ _____| __/ _ \ / _ \| / __| | | '_ \| |_ / _ \
  | |  ___) |__) |_____| || (_) | (_) | \__ \_| | | | |  _| (_) |
  |_| |____/____/       \__\___/ \___/|_|___(_)_|_| |_|_|  \___/

Script Version: 5.7.0 (2019-06-07)
Script License: Community (No support bought)
Support License: Community (No support plan bought)

Donate and support this script: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7ZRXLSC2UBVWE

------------------------------------------------------------------

Please wait... Script is working...

Performing self-tests as preventive measures against possible failures                                                                                                                     [ OK ]

Collecting necessary information for further tasks                                                                                                                                         [ FAILED ]

1 TeamSpeak 3 server instance found...

Collecting as much as possible information for following TeamSpeak 3 server instance: /opt/teamspeak
Validating collected information as preventive measures against possible failures
Wrong serveradmin password. Please set the correct one here: /opt/teamspeak/.password-file
Could not collect some information. Please fix the above error(s) to continue.

Cleaning up...

Summary of measured execution time for each step
Total script: 6s
Self-Test: 4s
Collecting Information: 2s
Validation: 0s
Cleanup: 0s

Thanks for using this script! Support the development of this script and donate: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7ZRXLSC2UBVWE

Hello, i have this problem. I´m sure the pasword is correct. 
Thank you.

**Comment by Sebi94nbg** [comment]
Hello @polida,
When the script reports, that the password is invalid, then it's invalid. It tries to login using this password ([see source code](https://github.com/TS3Tools/TS3UpdateScript/blob/master/TS3UpdateScript#L731-L775)): `login serveradmin SERVERADMIN_PASSWORD`

Please ensure, that your `/opt/teamspeak/.password-file` has only a single line (no spaces before or at the end and no line breaks).

You also can try to login with the password, which you get from the file:

```
cat /opt/teamspeak/.password-file
```

```
telnet localhost 10011
login serveradmin SERVERADMIN_PASSWORD
```

The login should return something with `msg=ok`.
