### ISSUE TITLE
teamspeak is a Service, Script isnt working

### ISSUE THREAD

**Issue by lukebleiwalker** [TS3Tools/TS3UpdateScript#107]
Hi, 

i have this error: Following instance needs an update, but is stopped and not touched by the script: /home/teamspeak/teamspeak3-server_linux_amd64

Privileges are correct, i think its because  ./ts3server_startscript.sh status give following return: No server running (ts3server.pid is missing).

Is it because i start it with systemd?

**Comment by gOOvER** [comment]
Server runing 4 real? This "ts3server.pid" is missing and i bet no server is running ;)

**Comment by lukebleiwalker** [comment]
you can join it if u want :D

**Comment by lukebleiwalker** [comment]
/lib/systemd/system/teamspeak3-server.service 

this is the way the server starts:

[Unit]
Description=TeamSpeak 3 Server
After=network.target

[Service]
Environment=LD_LIBRARY_PATH=/home/teamspeak/teamspeak3-server_linux_amd64/
WorkingDirectory=/home/teamspeak/teamspeak3-server_linux_amd64/
Type=simple
ExecStart=/home/teamspeak/teamspeak3-server_linux_amd64/ts3server inifile=ts3server.ini license_accepted=1
User=teamspeak
Group=teamspeak
StandardOutput=journal
StandardError=inherit
RestartSec=30

[Install]
WantedBy=multi-user.target

**Comment by Sebi94nbg** [comment]
Please also see this issue: #106 
He is also running the TS3 server as systemd service and it's working fine. :)

First of all: When you use systemd, please ensure, that you add a condition to avoid restarts while doing the update: `ConditionPathExists=!/home/teamspeak/teamspeak3-server_linux_amd64/.ts3updatescript.lock`

The file `.ts3updatescript.lock` will be always created, when the TS3UpdateScript starts the update process and when it finishes the update, it autom. deletes this file again.

I'm not sure about your posted systemd configuration, but it looks wrong. There is no PID file configured, which caused my systemd always to fail and not to work as expected. The type should be `forking` as far as I know and I'm not sure, why you even have this `Environment=` line there. This shouldn't be necessary at all, when the Linux server is configured properly.

And the most important thing: You should **always** use the `ts3server_startscript.sh` script to start and stop your TS3 server. The binary should be only used in very rare cases.

`license_accepted` is usually only once required: At the initial setup. So this can be removed as it has no effect.

Btw: You also can add this `inifile=ts3server.ini` parameter to your `ts3server_startscript.sh`. The TS3UpdateScript detects this at the update and will automatically ensure, that it will be added back after the update. :)

Before:
```
COMMANDLINE_PARAMETERS="${2}" #add any command line parameters you want to pass here
```

After:
```
COMMANDLINE_PARAMETERS="${2} inifile=ts3server.ini" #add any command line parameters you want to pass here
```

Here is my working systemd configuration (I've updated the paths with yours):

```
[Unit]
Description=TeamSpeak 3 Server
After=network.target
ConditionPathExists=!/home/teamspeak/teamspeak3-server_linux_amd64/.ts3updatescript.lock

[Install]
WantedBy=multi-user.target
Alias=teamspeak3-server.service

[Service]
User=teamspeak
Group=teamspeak
WorkingDirectory=/home/teamspeak/teamspeak3-server_linux_amd64/
ExecStart=/home/teamspeak/teamspeak3-server_linux_amd64/ts3server_startscript.sh start
ExecStop=/home/teamspeak/teamspeak3-server_linux_amd64/ts3server_startscript.sh stop
ExecReload=/home/teamspeak/teamspeak3-server_linux_amd64/ts3server_startscript.sh restart
PIDFile=/home/teamspeak/teamspeak3-server_linux_amd64/ts3server.pid
Restart=always
Type=forking
```

You might want to wait for your MySQL database, if you're using MySQL / MariaDB for the database: `After=network.target mysqld.service`
