### ISSUE TITLE
Could not detect version of latest TS3UpdateScript

### ISSUE THREAD

**Issue by poppm1408** [TS3Tools/TS3UpdateScript#108]
Hi there,
I'm using this script since years and i love it. Thanks for creating and maintaining it.

I moved my TS3server from VM to LXC. Also set up the server to connect to my local maradbserver. All works fine.
But after moving it, I'm never able to use the TS3UpdateScript anymore.
It failed on selftasting already and on can't figure out why. Yep, I've installed all requirements too.
May someone have an idea to get it back working again?

[debug.txt](https://github.com/TS3Tools/TS3UpdateScript/files/6249776/debug.txt)

If I run ./TS3UpdateScript --update-script the self-testing finish with [OK] but i can update every time again.

[debug_update.txt](https://github.com/TS3Tools/TS3UpdateScript/files/6249822/debug_update.txt)

**Comment by Sebi94nbg** [comment]
Hey @poppm1408 ,
Thanks for your feedback! Glad, that you like this script. :)

The script is checking for a newer version by fetching the CHANGELOG file from Github. Please ensure, that this command works and returns the CHANGELOG:
`wget -t 1 -T 1 https://raw.githubusercontent.com/TS3Tools/TS3UpdateScript/master/docs/CHANGELOG.md --no-check-certificate -q -O -`

When this doesn't work, this usually means, that your server has either a DNS problem or it's not able to access the internet. Please double-check this.

**Comment by poppm1408** [comment]
Hi Sebi,

1st: The command above does'nt work until . . . .
2nd: Thanks for the DNS resolving hint. When i've created my lxc's i just let the hypervisor choose the dns server and domain. The containers got the addresses from the host. So it tried to look up the names in my internal networks. I changed the values in the lxc settings and now it works like a charm.
3: Problem solved!!!

Thank you and best regards

**Comment by Sebi94nbg** [comment]
Great. Thanks for your feedback!
