### ISSUE TITLE
Error message when running?

### ISSUE THREAD

**Issue by 7quit** [TS3Tools/TS3UpdateScript#109]
Hello,

I have a question: when I run the file, I get two error messages, I just wanted to ask how I can fix it and whether the error messages are bad or not.

When I run **`./TS3UpdateScript --check`**, I get two error messages that two files or folders were not found. (See Appendix (1)).
![Error message 1](https://user-images.githubusercontent.com/45004106/128636692-f6f5d108-1cb3-4fa0-a5cc-37358c71f245.png)

And as soon as the next phase starts, which looks for the latest versions, I also get an error message from **`chown`** that it cannot find a file or folder again. (See Appendix (2)).
![Error message 2](https://user-images.githubusercontent.com/45004106/128636770-a860ce9e-ff57-4237-bbb5-91d009713d09.png)

**Comment by Sebi94nbg** [comment]
Hey,
The TS3UpdateScript supports bash autocompletion. Therefore, it installs the respective files and loads them afterwards.

Seems like as the source files didn't exist in your case and thus this installation task failed. Please ensure, that the following file exists in the same directory as the "TS3UpdateScript": https://github.com/TS3Tools/TS3UpdateScript/blob/master/.ts3updatescript

Then re-run the script and all should be fine.

As manual workaround / fix, you also can do this by your own manually:
```bash
cp .ts3updatescript /etc/bash_completion.d/ts3updatescript
chown root:root /etc/bash_completion.d/ts3updatescript
```

**Comment by 7quit** [comment]
Hey, thank you, it worked now.

**Comment by Sebi94nbg** [comment]
Great. Thanks for the update!
