### ISSUE TITLE
./TS3UpdateScript: line 1031: cd: $'/opt/ts3server/logs\r': No such file or directory

### ISSUE THREAD

**Issue by FirstS0ul** [TS3Tools/TS3UpdateScript#112]
Hi,

i start the script as root.
my TS3 instance is in /opt/ts3server.
my user "teamspeak3" has all rights and the server runs perfectly...

Script Version: 5.8.4 (2021-05-21)
Script License: Community (No support bought)
Support License: Community (No support plan bought)

Donate and support this script: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7ZRXLSC2UBVWE

------------------------------------------------------------------

Please wait... Script is working...

Fuehre Selbst-Tests als Preventivmassnahme gegen moegliche Fehler durch[ OK ]

Sammel notwendige Informationen fuer weitere Aufgaben[ OK ]

Alle gesammelten Informationen wurden erfolgreich als Praeventivmassnahme gegen moegliche Fehler validiert.[ INFO ]
./TS3UpdateScript: line 1031: cd: $'/opt/ts3server/logs\r': No such file or directory
1 TeamSpeak 3 Server Instanz gefunden.../ts3server/logs\r': No such file or directory
./TS3UpdateScript: line 1031: cd: $'/opt/ts3server/logs\r': No such file or directory
Sammel so viele wie moegliche Informationen fuer folgende TeamSpeak 3 Server Instanz: /opt/ts3server
1 Instanz fuer den Update Prozess...

Folgende Instanz benoetigt ein Update, ist jedoch gestoppt und wird nicht vom Skript angefasst: /opt/ts3server (Installierte Version: )

Raeume auf...

Zusammenfassung von gemessenen Zeiten fuer einzelne Schritte
Skript insgesamt: 9s
Selbst-Tests: 4s
Informationen sammeln: 4s
Validierung: 0s
Ausfuehrungsmechanismus: 0s
Aufraeumen: 0s

Vielen Dank fuer die Nutzung dieses Skripts! Unterstuetze die Weiterentwicklung dieses Skripts durch eine kleine Spende: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=
7ZRXLSC2UBVWE

**Comment by Sebi94nbg** [comment]
Hi @FirstS0ul ,
where are your TeamSpeak server logs located? And which permissions does the folder and the files inside the folder have?

The script currently detects this by either checking the variable `logpath` in the INI configuration file or by using the default `logs/` directory in the installation directory of the TeamSpeak server (in your case `/opt/ts3server/logs/`).

**Comment by FirstS0ul** [comment]
there we go. i had an error in my ts3server.ini. Now it works. Thanks!

**Comment by Sebi94nbg** [comment]
Ah, ok. Great. Have fun with the script. :)
