### ISSUE TITLE
Wrong Serveradmin password in .password-file

### ISSUE THREAD

**Issue by FirstS0ul** [TS3Tools/TS3UpdateScript#118]
Hi there!
my update script says there is the wrong password in the .password-file, but the file and the password ist 100% correct. i tested it with telnet. in the file are no spaces or other things.
What can we do now?

```
About: This is the most widely used and fastest shell script to update all your TeamSpeak 3 server instances.
Author: https://github.com/Sebi94nbg | Website: https://github.com/TS3Tools/TS3UpdateScript | facebook: www.facebook.com/TS3Tools
License: GNU GPLv3

 _______ _____ ____  _              _
|__   __/ ____|___ \| |            | |
   | | | (___   __) | |_ ___   ___ | |___
   | |  \___ \ |__ <| __/ _ \ / _ \| / __|
   | |  ____) |___) | || (_) | (_) | \__ \
   |_| |_____/|____/ \__\___/ \___/|_|___/

Script Version: 6.0.2
Donate and support this script: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7ZRXLSC2UBVWE

------------------------------------------------------------------

Please wait... Script is working...

Fuehre Selbst-Tests als Preventivmassnahme gegen moegliche Fehler durch                                                                        [ OK ]

Sammel notwendige Informationen fuer weitere Aufgaben                                                                                          [ FAILED ]

1 TeamSpeak 3 Server Instanz gefunden...

Sammel so viele wie moegliche Informationen fuer folgende TeamSpeak 3 Server Instanz: /home/ts3/ts3server
Validiere gesammelte Informationen als Praeventivmassnahme gegen moegliche Fehler
Falsches serveradmin Passwort. Bitte setze das korrekte hier: /home/ts3/ts3server/.password-file
Konnte einige Informationen nicht sammeln. Bitte behebe die oben genannten Fehler, um fortzufuehren.

Raeume auf...

Zusammenfassung von gemessenen Zeiten fuer einzelne Schritte
Skript insgesamt: 5s
Selbst-Tests: 5s
Informationen sammeln: 0s
Validierung: 0s
Aufraeumen: 0s

Vielen Dank fuer die Nutzung dieses Skripts! Unterstuetze die Weiterentwicklung dieses Skripts durch eine kleine Spende: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7ZRXLSC2UBVWE
```

**Comment by Sebi94nbg** [comment]
Hey @FirstS0ul,
Have you ensured, that your text editor doesn't saved any strange escape sequences or something in it?

The script tries to login using this password ([see source code](https://github.com/TS3Tools/TS3UpdateScript/blob/6.0.2/TS3UpdateScript#L532-L576)): `login serveradmin SERVERADMIN_PASSWORD`

Please ensure, that your `.password-file` has only a single line (no spaces before or at the end and no line breaks).

You also can try to login with the password, which you get from the file:

```
cat .password-file
```

```
telnet localhost 10011
login serveradmin SERVERADMIN_PASSWORD
```

The login should return something with `msg=ok`.

What does it return for you?

You can also create and share a debug report: `./TS3UpdateScript [your parameters] --debug debug.log`

Your ServerQuery password is censored in it - you can search for it in the file to be sure. :)

**Comment by FirstS0ul** [comment]
Hi.
yes i am sure, because i created the file through your script.
the .password-file is 100% correct.
And your advise with connecting through telnet does work. i can read the ful password without problems.
and yes it returns `msg=ok`

and here is the debuglog:
`+ ts3server /home/ts3/ts3server status
+ case $2 in
+++ which bash
+++ getOwnerOfTS3ServerFiles /home/ts3/ts3server
+++++ find /home/ts3/ts3server -name ts3server_startscript.sh
+++++ tail -1
+++++ sort
++++ stat --format=%U /home/ts3/ts3server/ts3server_startscript.sh
+++ OWNER=ts3
+++ [[ -n ts3 ]]
+++ echo -n ts3
++ su -s /usr/bin/bash -c 'cd /home/ts3/ts3server && ./ts3server_startscript.sh status && cd - > /dev/null' - ts3
+ RESULT='Server is running'
+ [[ Server is running =~ Server is running ]]
+ return 0
+ checkServeradminPassword $'0.0.0.0\r' 10011 /home/ts3/ts3server
+ '[' -f /home/ts3/ts3server/password-file ']'
+ '[' -f /home/ts3/ts3server/.password-file ']'
++ cat /home/ts3/ts3server/.password-file
+ SERVERADMIN_PASSWORD=CENSORED_PASS
+ chown root:root /home/ts3/ts3server/.password-file
+ cat
+ grep -Eo '=[a-z]+'
+ grep -Eo ok
+ head -1
+ grep -Eo 'error id=[0-9]+ msg=[a-z]+'
+ expect
++ cat RESULT.txt
+ RESULT=
+ rm RESULT.txt
+ [[ '' == \o\k ]]
+ return 1
+ echo 'Falsches serveradmin Passwort. Bitte setze das korrekte hier: /home/ts3/ts3server/.password-file'
+ VALIDATION_STATUS=1
+ read instanceInfo
++ date +%s
+ TIME_MEASUREMENT_VALIDATION_END=1669967932
`

**Comment by FirstS0ul** [comment]
i had 0.0.0.0 inside my ini file. i changed it to 127.0.0.1, but nothing changed.
i have the default SQLite database.
And here is the full debug log.
[debug.log](https://github.com/TS3Tools/TS3UpdateScript/files/10143331/debug.log)

**Comment by Sebi94nbg** [comment]
Yeah, then you probably have some hidden non-printed characters in your INI file. This would also explain these unexpected characters in the debug log.

However: I've improved the script to ignore any kind of non-printed characters like newlines or other things for the ServerQuery IP. I've also implemented this improvement for the ServerQuery port.

Please update your script to the version [6.0.3](https://github.com/TS3Tools/TS3UpdateScript/releases/tag/6.0.3) and give it a try. It should work now. :)

**Comment by FirstS0ul** [comment]
perfect! Works now. Thanks for the fix.

**Comment by Sebi94nbg** [comment]
Thanks for your feedback. You're welcome!
