### ISSUE TITLE
Permission denied for "ts3server_startup.sh start"

### ISSUE THREAD

**Issue by DavidRayner** [TS3Tools/TS3UpdateScript#12]
OS: Debian 8 Jessie
Script: v4.1.1
Attempting upgrade: 3.0.11.3 -> 3.0.11.4

I get "permission denied" for ts3server_startup.sh when the script attempts to restart  the ts3 server after successfully updating the ts3 server.

I also get "permission denied" if I try to start the server manually when the update script is running - I believe this is because "ts3server_startup.sh" enters a locked state when the update script calls: 
   ts3server_startup.sh stop

As soon as the update script exits (after failing), I can then start the server manually. But the update rolls-back.

Is there a way to free the lock on the file, so the script can start the server, and finish the update?

Or must I split the script into two sections, so I can start the server manually, and then continue the script?

Thanks

**Comment by Sebi94nbg** [comment]
Sorry, I didn't get you.

Have you renamed you "ts3server_startscript.sh" to "ts3server_startup.sh"? Please don't do that!

Have you changed something in any file of your TS3 server instance?

If the script executes the roll-back, your update to the latest version wasn't successful. Can you show me following outputs?

        $ ls -lha
        $ ./ts3server_startscript.sh status
        $ cat ts3server_startscript.sh
        $ cat logs/..._0.log (latest instance log file)

Thanks!

**Comment by DavidRayner** [comment]
Hi,

I have not renamed "ts3server_startscript.sh", I just referenced it incorrectly in my post, my bad..

Outputs: http://pastebin.com/raw.php?i=41YJpHLA

Thanks!

**Comment by Sebi94nbg** [comment]
I tried with 777 everywhere just to rule out file/dir permissions. I'll change that back shortly ;)

Very bad idea. :-1:

Regarding this line:

        -rw-r--r-- 1 root      root         5 Dec  8 19:03 ts3server.pid

Have you started your TS3 server as root? Please don't do that! Run it as user teamspeak, as you already assigned the permissions to that user.

Regarding this problem:

        ./ts3server_startscript.sh status
        Server seems to have died

Please stop or kill your TS3 server, make sure, that the ts3server.pid file does not exists anymore, change to the user account "teamspeak" and start the instance again. Now it should start.

        2015-12-08 20:05:25.306996|ERROR   |Query         |   | bind failed on 0.0.0.0:10011

This means, that the port is already in use. Stop your TS3 server instance and make sure, that the port is not in use anymore. Else make sure, that it is unused. You can check the port with following command:

        netstat -tulpen | grep 10011

If something is displayed to this port, it's in use.

**Comment by DavidRayner** [comment]
I think the first time I executed the script I did it as root user, which probably adjusted some permissions. I'll retinstall ts3 tomorrow when the server is empty. Thanks :+1:

**Comment by Sebi94nbg** [comment]
The TS3UpdateScript can just be executed as root, but the ts3server_startscript.sh needs to be executed as user "teamspeak" in your case.

**Comment by Sebi94nbg** [comment]
@DavidRayner Any updates to this issue/topic?

**Comment by Flofus** [comment]
Why you dont add a new User?
(In the Script)

**Comment by Sebi94nbg** [comment]
What do you mean with your suggestion?

**Comment by Flofus** [comment]
If you Start the Script as root the Script create a new account

**Comment by Sebi94nbg** [comment]
The TS3UpdateScript is a script to automate the update process. It will *not* change anything on the Linux system except file permissions for the TS3 server files.

Why? Companies don't like that and would wonder, why the script has added a new user or has changed something else on the server, what has nothing to do with the TeamSpeak 3 server. This is also not the task of the script. It's the task of the sysadmin. ;)

**Comment by Sebi94nbg** [comment]
Due no feedback, I'll close this issue now. Please create a new one, if you still have problems.
