### ISSUE TITLE
www.ts3-tools.info could not be reached.

### ISSUE THREAD

**Issue by mvoelz** [TS3Tools/TS3UpdateScript#122]
[www.ts3-tools.info](http://www.ts3-tools.info/) could not be reached.

**Comment by Sebi94nbg** [comment]
Yes, by design as announced with the release [`6.0.0`](https://github.com/TS3Tools/TS3UpdateScript/releases/tag/6.0.0).

> Starting with this release, the script is only licensed under GNU GPLv3. No additional software license is required.
> 
> Still active script licenses are still getting premium support. Otherwise, only community support will be provided in the future via Github issues.
> 
> Have fun and use all Enterprise features, you couldn't use before! :-)

Is there anything else or did you only want to mention this? If there is something else, I will write you a quick email.

**Comment by mvoelz** [comment]
thx for providing the enterprise features for free :)
sorry for reopening this issue, but it seems to me that with the domain being unavailable, the script fails here https://github.com/TS3Tools/TS3UpdateScript/blob/main/TS3UpdateScript#L2055 when not run with "--deactivate-host-alive-check" in version 6.0.4

since this seems to be the only usage of this domain, the check for this domain (2055-2058) could be removed i guess.

**Comment by Sebi94nbg** [comment]
Yes, correct. I'll remove it. Seems like as I've overseen this.

**Comment by Sebbo94BY** [comment]
The domain has been removed in the release [6.0.5](https://github.com/TS3Tools/TS3UpdateScript/releases/tag/6.0.5). :)
