### ISSUE TITLE
Following instance needs an update, but is stopped and not touched by the script

### ISSUE THREAD

**Issue by Cannonb4ll** [TS3Tools/TS3UpdateScript#26]
Script is not asking me to update, I just get the message in the title constantly.

My TS3 server version: 3.0.11.4

**Comment by Sebi94nbg** [comment]
You need to make sure, that the server files are owned by a non-root user and the server must be started as this user.

**Comment by Sebi94nbg** [comment]
Did it solve your problem?

**Comment by mightyBroccoli** [comment]
I have the same problem with this error message.
I ran the script as the user owning teamspeak, and all files are owned by this user.

Installed Version: 3.0.12.2

**Comment by Sebi94nbg** [comment]
@mightyBroccoli please send me a debug file via email address.

**Comment by mightyBroccoli** [comment]
@Sebi94nbg email sent.

**Comment by Sebi94nbg** [comment]
@mightyBroccoli in your case, the server seems to be not started.

Following command returns _No server running (ts3server.pid is missing)_:
`su -s /bin/bash -c 'cd /usr/local/bin/teamspeak3-server_linux_amd64 && ./ts3server_startscript.sh status && cd - > /dev/null' - teamspeak`

Can you see a ts3server.pid in your TeamSpeak 3 server directory? If yes, which permissions does the file has and who owns it?

**Comment by mightyBroccoli** [comment]
Thats the strange thing. The server is running. Thats the point. 

``` su -s /bin/bash -c 'cd /usr/local/bin/teamspeak3-server_linux_amd64 && ./ts3server_startscript.sh status'
Server is running ````

and I can see the ts3server.pid the permission is set like 
`-rw-r--r--  1 teamspeak teamspeak       5 Mar 12 13:41 ts3server.pid`

**Comment by Sebi94nbg** [comment]
As which user did you run the status command? I believe as root, because you haven't specified an user.

Please copy and paste my above command from https://github.com/TS3Tools/TS3UpdateScript/issues/26#issuecomment-195744901 and test it again.

**Comment by mightyBroccoli** [comment]
I ran this line and the server message is nevertheless the same. 
```
su teamspeak -s /bin/bash -c 'cd /usr/local/bin/teamspeak3-server_linux_amd64 && ./ts3server_startscript.sh status'
Server is running
```
But today I tried just for the fun of it your script again with the same line as usual (I aliased this command to make it even easier)
`su teamspeak -s /bin/bash -c 'cd /usr/local/bin/TS3UpdateScript/TS3UpdateScript --check`
and today the script ran perfectly without any problems. I did not change anything on the system and I am really surprised that it is working now.

**Comment by Sebi94nbg** [comment]
You've a very strange problem. Please let me know, if it's working for you tomorrow or if it's failing again.

**Comment by Sebi94nbg** [comment]
@mightyBroccoli are there any news about this issue?

Is it solved or do you still need any help.

**Comment by Sebi94nbg** [comment]
I'll close this issue, due no feedback.
