### ISSUE TITLE
Feature: Dynamic cronjob

### ISSUE THREAD

**Issue by TakeMeNL** [TS3Tools/TS3UpdateScript#28]
As for now the cron jobs are hard coded in the script. (CRONJOB_HOUR="3")

That's a bad thing i think, personally my servers do backups on 2 until 4 so when the cron job runs it only loads the system more and that's bad.

**Comment by Sebi94nbg** [comment]
You can just update the cronjob times to any other you want. Just edit the cronjob file: /etc/cron.d/TS3UpdateScript

What's your suggestion? What would it make much more better and cooler?

**Comment by Sebi94nbg** [comment]
Added functionality to new version.
