### ISSUE TITLE
Mail -c@domain 

### ISSUE THREAD

**Issue by TakeMeNL** [TS3Tools/TS3UpdateScript#34]
https://github.com/TS3Tools/TS3UpdateScript/blob/master/TS3UpdateScript#L3374

I'm running CentOS 6.7 and apperenly you don't need the -c to mail multiple email accounts.
The result at my end was a mail to you, a mail to me and a mail to -c@ who does not exists.

**Comment by Sebi94nbg** [comment]
Thanks for reporting this issue.

The issue has been fixed in the upcoming version.
