### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by KraXarN** [TS3Tools/TS3UpdateScript#35]
Update fails without helpful error message.
[Here](http://paste.ubuntu.com/19772540/)'s the output of `./TS3UpdateScript --check --debug error.txt`

**Comment by Sebi94nbg** [comment]
Can you post your instance log file, please?

Following was returned by the server, when the script tried to start it:

> Starting the TeamSpeak 3 server
> TeamSpeak 3 server could not start

The following command has tried to started your instance:
`su -s /bin/bash -c 'cd /mnt/sdb5/ts3 && ./ts3server_startscript.sh start 2> /dev/null && cd - > /dev/null' - kraxarn`

**Comment by gOOvER** [comment]
warn 'expect is not found. Please install this package'
+ printf 'expect is not found. Please install this package\n'


Sooo for me this is a very clear Error ;)

**Comment by KraXarN** [comment]
Now it asked for the serveradmin password in .password-file and after entering it, it still fails with the same error. Can upload a new log if needed

**Comment by Sebi94nbg** [comment]
I'm not sure, what you mean. The script stops the server successful as you can see in your debug file:

> Temporary server passwords were not backuped, because you've disabled it or whether telnet nor expect is installed.
> TeamSpeak 3 server instance stopped for update process.
> Backup created successful.
> TeamSpeak 3 server instance was updated successful.
> TeamSpeak 3 server could not start
> Could not start TeamSpeak 3 server instance.
> Update failed. Rollback to the version '3.0.11.1'.
> TeamSpeak 3 server started, for details please view the log file
> TeamSpeak 3 server instance was started successful.
> Backup was deleted successful.

If you install telnet **and** expect, the script will work more efficient and it will require the serveradmin password, due it's detecting some information with ServerQuery commands then.

In your case, the TS3 server could not start. Please post your instance log file of the TeamSpeak 3 server. It's located in _/mnt/sdb5/ts3/logs/_. There you'll find a file with the suffix "__0.log_".

**Comment by KraXarN** [comment]
That's not the issue. The server starts just fine, but is not updated.

**Comment by Sebi94nbg** [comment]
I believe, you didn't read the output carefully, or?

> Temporary server passwords were not backuped, because you've disabled it or whether telnet nor expect is installed.
> TeamSpeak 3 server instance stopped for update process.
> Backup created successful.
> **TeamSpeak 3 server instance was updated successful.**
> TeamSpeak 3 server could not start
> **Could not start TeamSpeak 3 server instance.**
> **Update failed. Rollback to the version '3.0.11.1'.**
> TeamSpeak 3 server started, for details please view the log file
> **TeamSpeak 3 server instance was started successful.**
> Backup was deleted successful.

It has updated your instance successful, but was unable to start it and due of this, it restored your old version of backup and started this instead of having a non-working TS3 server. ;)

**Comment by Sebi94nbg** [comment]
Any news? Do you want to show me your log file of the TS3 server?

**Comment by KraXarN** [comment]
[Here](http://paste.ubuntu.com/19944850/)'s the TS3 log file created

**Comment by Sebi94nbg** [comment]
That's the log file of your server release 3.0.11.1. I would need the log file for the release, on which you want to update and isn't able to start.

You also should fix this error:
> TS3ANetwork::ResolveHostName failed error: -3 (Temporary failure in name resolution) 11

**Comment by KraXarN** [comment]
That's the server I want to update. As I told you, there's no server that isn't able to start

**Comment by Sebi94nbg** [comment]
Ok, let me implement a further debug feature, to get more details about the failure.

**Comment by Sebi94nbg** [comment]
I've updated the TS3UpdateScript. Please update yours to the version [4.6.0](https://github.com/TS3Tools/TS3UpdateScript/blob/master/docs/CHANGELOG.md#version-460) and send me a new debug file.

**Comment by Sebi94nbg** [comment]
Any news, @KraXarN?

**Comment by KraXarN** [comment]
Currently not able to try it out, will try it out next weekend hopefully

**Comment by Sebi94nbg** [comment]
Hope, your weekend was good @KraXarN. :)

Do you have any news for me?

**Comment by Sebi94nbg** [comment]
Closed, due of no further feedback.

**Comment by KraXarN** [comment]
Sorry, lost interest in the script. Will come back if I ever want to try it again and see if it's fixed then.
