### ISSUE TITLE
Update script doesn't detect newer installed version.

### ISSUE THREAD

**Issue by tadhgfitzgerald** [TS3Tools/TS3UpdateScript#36]
When I run the latest TS Update Script (4.6.0) it asks do I want to "update" to a version that's older than that currently installed. This doesn't affect me, just said I'd let you know.

```
1 TeamSpeak 3 server instance found...

Collecting as much as possible information for following TeamSpeak 3 server instance: /opt/teamspeak3-server
1 instance for update process...
############################################################################
	Do you want to update this instance to the following version? 3.0.11.4

	Installation Directory: /opt/teamspeak3-server
	Installed Version: 3.0.12.4 (Build: 1461597405)
	Installed Platform: Linux
	Installed Architecture: amd64

	Instance Log Files: /opt/teamspeak3-server/logs
	Instance TSDNS Binary: /opt/teamspeak3-server/tsdns/tsdnsserver
	TSDNS Status: Inactive

	Owner: teamspeak3-user (UID: 1000)
	Group: teamspeak3-user (GID: 1000)

	ServerQuery IP: 0.0.0.0
	ServerQuery Port: 10011

	Database Type: MariaDB
############################################################################
Please answer: ([y]es/[n]o) n
Instance will not be updated.
```

**Comment by Sebi94nbg** [comment]
That's very strange. Usually, it's the behaviour of an out-dated TS3UpdateScript, but yours looks like a newer one and you said, you're using the v4.6.0. 

Due I'm on vocatation until mid of next week, I'm unfortunately not able to verify it.

Which parameters did you use? And please send or attach an debug file. Thanks!

**Comment by tadhgfitzgerald** [comment]
I investigated some more and I think the problem was my misunderstanding of what "--latest-release" parameter does. I was using this parameter and config/config.all was set to 3.0.11.4. Sorry about that!

**Comment by Sebi94nbg** [comment]
Ah, ok. Yeah, that explains it. No problem. ;)
