### ISSUE TITLE
Update Script Failure

### ISSUE THREAD

**Issue by chiefstank** [TS3Tools/TS3UpdateScript#37]
./TS3UpdateScript: line 3530: unexpected EOF while looking for matching `''
./TS3UpdateScript: line 3534: syntax error: unexpected end of file

**Comment by Sebi94nbg** [comment]
Which version of the script are you using? The latest version of the script does only have 3525 lines.

Please download it again and make sure, that the download was successful.

**Comment by chiefstank** [comment]
I was using Script Version: 4.5.0 (2016-07-02)

After cloning there not longer is an error due to no new version available.

FYI this happened with another previous version, perhaps the one published February (can't remember). Just did a new clone to sort it temporarily.
