### ISSUE TITLE
Password error even if .password-file has correct password

### ISSUE THREAD

**Issue by erdihu** [TS3Tools/TS3UpdateScript#52]
I added serveradmin password to the stated file but the script still gives authentication error during --check command. I am sure that password is correct since I can login with stated password using Yatqa.

`Wrong serveradmin password. Please set the correct one here: /usr/local/teamspeak3/.password-file`

**Comment by Sebi94nbg** [comment]
Please try to login using ``telnet`` and your der password:
``telnet SERVER_QUERY_IP SERVER_QUERY_PORT``
``login serveradmin PASSWORD``

Use the ServerQuery IP and Port, which see displayed in the overview by executing the script. 

If it works, please send me a debug file using the parameter ``--debug``.

**Comment by erdihu** [comment]
`login serveradmin password` returns  `error id=0 msg=ok` so I assume it works.

Here's the output of debug: https://paste.ee/p/OTsUc

**Comment by Sebi94nbg** [comment]
Can you please change the line [612](https://github.com/TS3Tools/TS3UpdateScript/blob/master/TS3UpdateScript#L612) to this here?

`	) | expect 2> /dev/null > RESULT.txt
`
...and add this line directly under this line:

`	cp RESULT.txt RESULT_SERVERADMIN_CHECK.txt`

Now run the script once again and post the content of the ``RESULT_SERVERADMIN_CHECK.txt`` here. Please note, that you censor your serveradmin password.

**Comment by erdihu** [comment]
`RESULT_SERVERADMIN_CHECK.txt` comes out as empty after --check command.

**Comment by Sebi94nbg** [comment]
Uhm, ok. Then please also remove ``2> /dev/null`` from the line 612.

It's maybe throwing an error.

**Comment by erdihu** [comment]
```
Please wait... Script is working...

Performing self-tests as preventive measures against possible failures[ .. ]

                                                                      [ OK ]

Collecting necessary information for further tasks                    [ .. ]

./TS3UpdateScript: line 612: expect: command not found
                                                                      [ FAILED ]

1 TeamSpeak 3 server instance found...

Collecting as much as possible information for following TeamSpeak 3 server instance: /usr/local/teamspeak3
Validating collected information as preventive measures against possible failures
Wrong serveradmin password. Please set the correct one here: /usr/local/teamspeak3/.password-file
Could not collect some information. Please fix the above error(s) to continue.

Cleaning up...

Summary of measured execution time for each step
Total script: 11s
Self-Test: 4s
Cleanup: 0s

```
`RESULT_SERVERADMIN_CHECK.txt` is still empty.

**Comment by Sebi94nbg** [comment]
I understand... You haven't installed ``expect`` and due of that, the serveradmin password can't be checked.

``./TS3UpdateScript: line 612: expect: command not found``

I've changed how to [check installed packages](https://github.com/TS3Tools/TS3UpdateScript/blob/master/TS3UpdateScript#L271-L285) in [TS3UpdateScript v5.2.0](https://github.com/TS3Tools/TS3UpdateScript/blob/master/docs/CHANGELOG.md#version-520) and I believe, it's not perfect.

> * Improved checking of required packages: The script will now display all missing packages instead of a single one at every execution

I'll improve this and let you know, when it's done.

**Comment by erdihu** [comment]
Installing expect solved the issue. Thank you!

**Comment by Sebi94nbg** [comment]
I'm not sure, how it could happen, that it tries to check the serveradmin password. I've just tested it in multiple ways and it always returned me, that expect is missing, but I never got such an error.

Also with only the ``--check`` parameter, it should just jump over this task, if there is only telnet or expect installed. Only if both packages are installed and/or you've used the parameter ``--inform-online-clients``, it should explicit check this password.

However... To make sure, that it won't happen anymore, I've improved the function ``checkdeps`` to prevent this strange issue in future. Due of that, that I couldn't reproduce this problem, I couldn't really verify the fix.

I would be so glad, if you could verify it, once I've released the new version.

**Comment by Sebi94nbg** [comment]
TS3UpdateScript v5.2.2 has been released.

**Comment by erdihu** [comment]
5.2.2 is working as intended. Removing expect did not affect the operation of --check. --inform-online-clients threw missing package error. Looks like the problem has been solved.

**Comment by Sebi94nbg** [comment]
Perfect! Thanks for your feedback!
