### ISSUE TITLE
Getting temporary server passwords taking too long.

### ISSUE THREAD

**Issue by boindil** [TS3Tools/TS3UpdateScript#57]
```
Trying to backup temporary server passwords. Please wait...
^CCould not backup temporary server passwords. Don't worry. You may just don't had any.
```

After waiting about 2 minutes, I pressed CTRL+C. The script proceeded fine after that.

I'm running 9 virtual servers (NPL) and all previous updates were done within seconds.

**Comment by Sebi94nbg** [comment]
Well with 9 virtual servers it can take a few minutes, but if it was running faster before, there is maybe a problem yes.

Please insert the following code to the line [1483](https://github.com/TS3Tools/TS3UpdateScript/blob/master/TS3UpdateScript#L1483):
`cp TEMP_SERVERTEMPPASSWORDLIST.txt BCK_TEMP_SERVERTEMPPASSWORDLIST.txt`

Then execute the script once more, break it, if it takes to long for you and at the end, you should see a file called `BCK_TEMP_SERVERTEMPPASSWORDLIST.txt`. Show me the content of it please.

**Comment by Sebi94nbg** [comment]
Any feedback would very help. :)

**Comment by Sebi94nbg** [comment]
I'll close this issue due of no feedback.

**Comment by boindil** [comment]
Hi,
I did another update today, and the `TEMP_SERVERTEMPPASSWORDLIST.txt` is empty (0 Byte), no `BCK_TEMP_SERVERTEMPPASSWORDLIST.txt` is created. CTRL+C is the only option.

**Comment by Sebi94nbg** [comment]
Hi, are you using the latest TS3UpdateScript? It's version 5.4.3.

Please provide these information too: lsb_release -a

**Comment by boindil** [comment]
Hi,
yes I did update the TS3UpdateScript to the latest version prior to updating my TS3Server.

```
[root@services ~]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.2.1511 (Core)
Release:        7.2.1511
Codename:       Core
```

**Comment by Sebi94nbg** [comment]
Are you able to poke clients?
`./TS3UpdateScript --test-inform-online-clients`

**Comment by boindil** [comment]
Hi,
it took quite some time, but yes. I am still unsure why this process took so long.

```
Summary of measured execution time for each step
Total script: 229s
Self-Test: 4s
Collecting Information: 3s
Validation: 0s
Execution Mechanism: 222s
Collecting information for poke mechanism and poking all online clients: 222s
Poking all online clients: 11s
Cleanup: 0s
```

**Comment by Sebi94nbg** [comment]
How many clients were on the server at this time?

**Comment by boindil** [comment]
I dont know for sure, but it should be about 20-30 clients

**Comment by Sebi94nbg** [comment]
Ok, than it's only the telnet connection, which fetches all the information, which is such slow.

I'm not sure why it is as it is, but depending on the server and it's operating system it takes more or less time to get everything. On a Raspberry Pi for example it takes up to the double time of yours.

But a Raspberry is something special. There is the server started, but you're only able to join after around 1 minute, even when the server is already up since 30 seconds.

**Comment by boindil** [comment]
Hi,
the server itself isn't slow. Network transfer speed is about 12MB/s from/to external source, the server is virtualized using OpenVZ and can use all 4/8 cores of a Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz CPU. The server uses about 150M of 1024M of RAM and the CPU is mainly idle (about 1-2% processor usage).

Weird thing is, that is was once lightning-fast and now ...

For comparison to your RPi excample: Full server reboot takes about 20-30 seconds with a few other small services such as IRC installed. The TS3 itself needs 6.5 seconds to be started and users able to connect.

**Comment by Sebi94nbg** [comment]
Sorry for the delay. I've checked the code of the TS3UpdateScript, but unfortunately, this code was only improved to prevent some bugs on different operating systems.

Well, I believe, this slowness depends on the TeamSpeak 3 server software and not the TS3UpdateScript. They have fixed a lot of security issues and bugs and this may be the cause, why ServerQuery connections are now a bit slower.

I'll check this out and get in touch with TeamSpeak, if required.

**Comment by boindil** [comment]
Hm..
well maybe Teamspeak has now some sort of flood-control enabled, so that the server-queries are taking longer? That would indeed explain everything.

**Comment by Sebi94nbg** [comment]
I've tried to reproduce the issue or even to find a performance lack, but I couldn't find anything, which could be the reason.

I'm getting similar time meassurements from an old and the latest TeamSpeak 3 server software release:
```
# --test-inform-online-clients
# 3.0.13.4 on Linux

Summary of measured execution time for each step
Total script: 27s
Self-Test: 4s
Collecting Information: 3s
Validation: 0s
Execution Mechanism: 20s
Collecting information for poke mechanism and poking all online clients: 20s
Poking all online clients: 0s
Cleanup: 0s

# --test-inform-online-clients
# 3.0.13.6 on Linux

Summary of measured execution time for each step
Total script: 28s
Self-Test: 4s
Collecting Information: 3s
Validation: 0s
Execution Mechanism: 21s
Collecting information for poke mechanism and poking all online clients: 21s
Poking all online clients: 0s
Cleanup: 0s
```

Here is a full update process:
```
# --check --delete-old-logs --inform-online-clients
# 3.0.11.2 -> 3.0.13.6 on Linux

Summary of measured execution time for each step
Total script: 62s
Self-Test: 4s
Collecting Information: 3s
Validation: 0s
Execution Mechanism: 55s
Backuping temporary server passwords: 10s
Formatting temporary server passwords for restore: 0s
Collecting information for poke mechanism and poking all online clients: 21s
Poking all online clients: 0s
Cleanup: 0s
```

I've added some new time measurements for backuping temporary server passwords. Please update your TS3UpdateScript to the latest version `5.5.0` in order to see these new statistics. Next time, when you update your TeamSpeak 3 server instance, you'll find some new statistics like this:
```
Backuping temporary server passwords: 10s
Formatting temporary server passwords for restore: 0s
```
Just show me these stats next time. Thanks!

**Comment by Sebi94nbg** [comment]
I'll close this issue due of no further feedback and due of that, that it's working as expected.
