### ISSUE TITLE
Found instance but is stopped where it is not...

### ISSUE THREAD

**Issue by Memphizzz** [TS3Tools/TS3UpdateScript#58]
Hi,

after updating to the new version of the script I get the following on --check:
Following instance needs an update, but is stopped and not touched by the script: /home/XYZ (Installed Version: 3.0.11.4).
But the service is running...

Any Ideas?

**Comment by Sebi94nbg** [comment]
Hi @Memphizzz,

please provide an error log file by adding the additional `--debug` parameter.

Thank you.

**Comment by Memphizzz** [comment]
Hi @Sebi94nbg,

thanks for the hint, using it i was able to find the issue. The ts3_server_startscript.sh returns "Server seems to have died" when doing the kill -0 check on the ts3server.pid. I can't figure out why though.. Did the kill command change in xenial?

**Comment by Memphizzz** [comment]
I think i found it:
su -s /bin/bash -c 'cd /home/teamspeak3/teamspeak3 && ./ts3server_startscript.sh status && cd - > /dev/null' 
this line, gives me authentication failures when trying it manually. Once i add sudo in front of it it works.
Explanation might be this: http://askubuntu.com/questions/446570/why-does-su-fail-with-authentication-error

**Comment by Sebi94nbg** [comment]
The script is tested on Xenial and is working fine. Your mentioned command isn't the full command. There is at least the username missing as which it will be executed.

Please make sure, that your `root` and `teamspeak3` user has a password set.

**Comment by Memphizzz** [comment]
Thanks that was it! Both users didn't have a password set. For anyone facing the same issue, you can check if your users have a password set using: passwd -S <user>. If the result shows a L or NP after the username you have to set it.

**Comment by Sebi94nbg** [comment]
Thanks for your feedback and especially the solution!

**Comment by Memphizzz** [comment]
You're welcome! Thanks for the great script ;)
