### ISSUE TITLE
Script Won't Ask To Update TS3 Server

### ISSUE THREAD

**Issue by dado3272** [TS3Tools/TS3UpdateScript#61]
Hello, I downloaded this script and it is giving me this error:
Following instance needs an update, but is stopped and not touched by the script.
I've changed my ts3server.pid permissions to 666 but the problem still persists.
How can i solve this?
[log.txt](https://github.com/TS3Tools/TS3UpdateScript/files/705573/log.txt)

**Comment by Sebi94nbg** [comment]
Hi @dado3272 ,
in your case, the `ts3server_startscript.sh` script returns following:
`Server seems to have died`

The TS3UpdateScript uses following code to identify this:
`su -s /bin/bash -c 'cd /usr/local/teamspeak && ./ts3server_startscript.sh status && cd - > /dev/null' - teamspeak`

Please make sure, that you've started your TS3 server instance using the user `teamspeak`. If you log in as user `teamspeak` and execute `./ts3server_startscript.sh status`, this script should return you a text like this, when the server is up and running: `Server is running`

It might be useful to know, how your directory looks like at the moment: `ls -lha /usr/local/teamspeak/`

**Comment by dado3272** [comment]
Hi, I've started the server with the user teamspeak and now the scripts is working. Before i was running it as root.
Thanks for your help.

**Comment by Sebi94nbg** [comment]
Excellent. Thanks for your feedback!
