### ISSUE TITLE
Script does not work on Debian 8.9

### ISSUE THREAD

**Issue by penderes** [TS3Tools/TS3UpdateScript#70]
Hi all,

I have a problem running the script.

The error I get is the following:
Collecting as much as possible information for following TeamSpeak 3 server instance: /usr/local/ts3/teamspeak3-server_linux_amd64
1 instance for update process...
############################################################################
        Do you want to update this instance to the following version? 

        Installation Directory: /usr/local/ts3/teamspeak3-server_linux_amd64
        Installed Version: 3.0.13.6 (Build: Unknown)
        Installed Platform: Linux
        Installed Architecture: amd64

        Instance Log Files: /usr/local/ts3/teamspeak3-server_linux_amd64/logs/
        Instance TSDNS Binary: /usr/local/ts3/teamspeak3-server_linux_amd64/tsdns/tsdnsserver
        TSDNS Status: warning: nothing to read
internal error: stack underflow
Inactive

        Owner: ts3 (UID: 1000)
        Group: staff (GID: )

        Database Type: SQLite
############################################################################
Please answer: ([y]es/[n]o) y
Temporary server passwords were not backuped, because you've disabled it or whether telnet nor expect is installed.
warning: nothing to read
internal error: stack underflow
TeamSpeak 3 server instance stopped for update process.
Backup created successful.
tar: Das sieht nicht wie ein „tar“-Archiv aus.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cp: der Aufruf von stat für „teamspeak3-server_linux-amd64/*“ ist nicht möglich: Datei oder Verzeichnis nicht gefunden
Could not update TeamSpeak 3 server instance. Do you have enough space on '/usr/local/ts3/teamspeak3-server_linux_amd64'?
./TS3UpdateScript: Zeile 2128: expect: Kommando nicht gefunden.
Due of the failed update, the TS3UpdateScript has created a debug report in /usr/local/ts3/teamspeak3-server_linux_amd64/20170831-1225-ts3us-debug-report.md
Update failed. Rollback to the version '3.0.13.6'.
TeamSpeak 3 server instance was started successful.
Backup was deleted successful.

Cleaning up...

Summary of measured execution time for each step
Total script: 11s
Self-Test: 5s
Collecting Information: 0s
Validation: 0s
Execution Mechanism: 6s
Cleanup: 0s

It seems that the script has a problem with unpacking the file? Do you have any ideas how I can fix this?

Thanks in advance for any help.

Debug log attached below:
---------
# TS3tools TS3UpdateScript Debug Report

Date and time of report: 20170831-1225
TS3UpdateScript Installation Path: /usr/local/ts3/TS3UpdateScript
TS3UpdateScript Version: 5.6.1
TS3UpdateScript Parameters: --check

## TS3UpdateScript output

Please copy and paste the output of the shell below this line and/or attach a debug file of this script.

## Operating System Details

Distributor ID:	Debian
Description:	Debian GNU/Linux 8.9 (jessie)
Release:	8.9
Codename:	jessie

Linux 4bez5ri 2.6.32-042stab120.20 #1 SMP Fri Mar 10 16:52:50 MSK 2017 x86_64 GNU/Linux

### root User locale

LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=

### ts3 User locale

LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=

## TS3 Update Details

Update path: 3.0.13.6 -> 
Instance path: /usr/local/ts3/teamspeak3-server_linux_amd64
Type Of Files Storage: Local disk
Installed TS3 Server Version: 3.0.13.6
Installed TS3 Server Build: Unknown
Installed TS3 Server Platform: linux
TS3 Server Instance Log Path: /usr/local/ts3/teamspeak3-server_linux_amd64/logs/
TS3 Server Architecture: amd64
*nix Owner: ts3 (UID 1000)
*nix Group: staff (GID )
Database Type: SQLite
Update Text (Manually): The server will be updated to the version  right now.
Update Text (Cronjob): The server will be updated to version  in 5 minutes.
Ignore Clients: 1,
Ignore ServerGroups: 1,2,

### ts3server.ini

ts3server.ini file does not exist

### Instance Log file

ï»¿2017-08-31 16:21:39.598157|INFO    |ServerLibPriv |   |TeamSpeak 3 Server 3.0.13.6 (2016-11-08 08:48:33)
2017-08-31 16:21:39.598455|INFO    |ServerLibPriv |   |SystemInformation: Linux 2.6.32-042stab120.20 #1 SMP Fri Mar 10 16:52:50 MSK 2017 x86_64 Binary: 64bit
2017-08-31 16:21:39.598493|INFO    |ServerLibPriv |   |Using hardware aes
2017-08-31 16:21:39.769373|INFO    |DatabaseQuery |   |dbPlugin name:    SQLite3 plugin, Version 3, (c)TeamSpeak Systems GmbH
2017-08-31 16:21:39.769502|INFO    |DatabaseQuery |   |dbPlugin version: 3.11.1
2017-08-31 16:21:39.888634|INFO    |DatabaseQuery |   |checking database integrity (may take a while)
2017-08-31 16:21:40.175207|WARNING |Accounting    |   |Unable to find valid license key, falling back to limited functionality
2017-08-31 16:21:41.518008|INFO    |              |   |Puzzle precompute time: 1186
2017-08-31 16:21:41.519047|INFO    |FileManager   |   |listening on 0.0.0.0:30033, :::30033
2017-08-31 16:21:41.882888|INFO    |CIDRManager   |   |updated query_ip_whitelist ips: 127.0.0.1/32, 185.82.23.29/32, ::1/128, 
2017-08-31 16:21:41.883263|INFO    |Query         |   |listening on 0.0.0.0:10011, :::10011
2017-08-31 16:25:56.093758|INFO    |ServerMain    |   |Received signal SIGTERM, shutting down.

### Permissions in /usr/local/ts3/teamspeak3-server_linux_amd64

/usr/local/ts3/teamspeak3-server_linux_amd64/
insgesamt 12M
drwxr-sr-x 9 ts3  staff 4,0K Aug 31 12:25 .
drwxr-sr-x 4 ts3  staff 4,0K Aug 31 11:39 ..
-rw-r--r-- 1 root staff 3,4K Aug 31 12:25 20170831-1225-ts3us-debug-report.md
-rw-r--r-- 1 ts3  staff  50K Nov  8  2016 CHANGELOG
drwxr-sr-x 3 ts3  staff 4,0K Nov  8  2016 doc
drwx--S--- 4 ts3  staff 4,0K Okt 14  2016 files
-rwxr-xr-x 1 ts3  staff 978K Nov  8  2016 libts3db_mariadb.so
-rwxr-xr-x 1 ts3  staff 2,1M Nov  8  2016 libts3db_sqlite3.so
-rw-r--r-- 1 ts3  staff  36K Nov  8  2016 LICENSE
drwx--S--- 2 ts3  staff 4,0K Aug 31 12:21 logs
-rw-r--r-- 1 ts3  staff    0 Okt 14  2016 query_ip_blacklist.txt
-rw-r--r-- 1 ts3  staff   27 Okt 14  2016 query_ip_whitelist.txt
drwxr-sr-x 2 ts3  staff 4,0K Nov  8  2016 redist
drwxr-sr-x 2 ts3  staff 4,0K Nov  8  2016 serverquerydocs
drwxr-sr-x 5 ts3  staff  12K Nov  8  2016 sql
-rwxr-xr-x 1 ts3  staff 7,8M Nov  8  2016 ts3server
-rwxr-xr-x 1 ts3  staff  129 Nov  8  2016 ts3server_minimal_runscript.sh
-rw-r--r-- 1 ts3  staff 304K Aug 31 12:25 ts3server.sqlitedb
-rwxr-xr-x 1 ts3  staff 2,6K Nov  8  2016 ts3server_startscript.sh
-rw-r--r-- 1 ts3  staff    0 Aug 31 12:25 .ts3updatescript.lock
drwxr-sr-x 2 ts3  staff 4,0K Nov  8  2016 tsdns

/usr/local/ts3/teamspeak3-server_linux_amd64/redist
insgesamt 308K
drwxr-sr-x 2 ts3 staff 4,0K Nov  8  2016 .
drwxr-sr-x 9 ts3 staff 4,0K Aug 31 12:25 ..
-rwxr-xr-x 1 ts3 staff 300K Nov  8  2016 libmariadb.so.2

/usr/local/ts3/teamspeak3-server_linux_amd64/sql
insgesamt 628K
drwxr-sr-x 5 ts3 staff  12K Nov  8  2016 .
drwxr-sr-x 9 ts3 staff 4,0K Aug 31 12:25 ..
-rw-r--r-- 1 ts3 staff   65 Nov  8  2016 ban_delete.sql
-rw-r--r-- 1 ts3 staff  360 Nov  8  2016 ban_insert.sql
-rw-r--r-- 1 ts3 staff   48 Nov  8  2016 ban_list.sql
-rw-r--r-- 1 ts3 staff   52 Nov  8  2016 binding_delete.sql
-rw-r--r-- 1 ts3 staff   63 Nov  8  2016 bindings_insert.sql
-rw-r--r-- 1 ts3 staff   44 Nov  8  2016 bindings_list.sql
-rw-r--r-- 1 ts3 staff  497 Nov  8  2016 channel_delete_bulk.sql
-rw-r--r-- 1 ts3 staff  415 Nov  8  2016 channel_delete.sql
-rw-r--r-- 1 ts3 staff  309 Nov  8  2016 channel_insert_bulk_fixup.sql
-rw-r--r-- 1 ts3 staff   78 Nov  8  2016 channel_insert_bulk_mapping.sql
-rw-r--r-- 1 ts3 staff  178 Nov  8  2016 channel_insert_bulk.sql
-rw-r--r-- 1 ts3 staff   97 Nov  8  2016 channel_insert.sql
-rw-r--r-- 1 ts3 staff  191 Nov  8  2016 channel_properties_bulk_insert.sql
-rw-r--r-- 1 ts3 staff  254 Nov  8  2016 channel_server_list_properties_bulk.sql
-rw-r--r-- 1 ts3 staff   79 Nov  8  2016 channel_server_list.sql
-rw-r--r-- 1 ts3 staff   88 Nov  8  2016 channel_update_parentid.sql
-rw-r--r-- 1 ts3 staff   96 Nov  8  2016 client_clear_traffic_stats.sql
-rw-r--r-- 1 ts3 staff   67 Nov  8  2016 client_count_by_serverid.sql
-rw-r--r-- 1 ts3 staff  346 Nov  8  2016 client_delete_prune.sql
-rw-r--r-- 1 ts3 staff  597 Nov  8  2016 client_delete.sql
-rw-r--r-- 1 ts3 staff   76 Nov  8  2016 client_get_by_id.sql
-rw-r--r-- 1 ts3 staff   91 Nov  8  2016 client_get_by_name_or_uid.sql
-rw-r--r-- 1 ts3 staff  343 Nov  8  2016 client_get_by_serverid_bulk.sql
-rw-r--r-- 1 ts3 staff   76 Nov  8  2016 client_get_by_serverid_limit.sql
-rw-r--r-- 1 ts3 staff   51 Nov  8  2016 client_get_by_serverid.sql
-rw-r--r-- 1 ts3 staff   92 Nov  8  2016 client_get_by_uid.sql
-rw-r--r-- 1 ts3 staff   50 Nov  8  2016 client_get.sql
-rw-r--r-- 1 ts3 staff  151 Nov  8  2016 clientid_get_by_name_pw_serverid.sql
-rw-r--r-- 1 ts3 staff  121 Nov  8  2016 clientid_get_by_name_pw.sql
-rw-r--r-- 1 ts3 staff   75 Nov  8  2016 client_insert_bulk_mapping.sql
-rw-r--r-- 1 ts3 staff  318 Nov  8  2016 client_insert_bulk.sql
-rw-r--r-- 1 ts3 staff  189 Nov  8  2016 client_insert.sql
-rw-r--r-- 1 ts3 staff  188 Nov  8  2016 client_properties_bulk_insert.sql
-rw-r--r-- 1 ts3 staff  158 Nov  8  2016 client_update_login_info.sql
-rw-r--r-- 1 ts3 staff  107 Nov  8  2016 client_update_name.sql
-rw-r--r-- 1 ts3 staff  173 Nov  8  2016 client_update_stats.sql
-rw-r--r-- 1 ts3 staff  276 Nov  8  2016 client_update_traffic_stats.sql
-rw-r--r-- 1 ts3 staff  104 Nov  8  2016 complain_delete_all.sql
-rw-r--r-- 1 ts3 staff   91 Nov  8  2016 complain_delete_prune.sql
-rw-r--r-- 1 ts3 staff  160 Nov  8  2016 complain_delete.sql
-rw-r--r-- 1 ts3 staff   54 Nov  8  2016 complain_get_by_serverid.sql
-rw-r--r-- 1 ts3 staff  267 Nov  8  2016 complain_insert.sql
drwxr-sr-x 2 ts3 staff 4,0K Nov  8  2016 create_mariadb
drwxr-sr-x 2 ts3 staff 4,0K Nov  8  2016 create_sqlite
-rw-r--r-- 1 ts3 staff   81 Nov  8  2016 custom_delete_by_clientid.sql
-rw-r--r-- 1 ts3 staff  100 Nov  8  2016 custom_get_by_ident.sql
-rw-r--r-- 1 ts3 staff   82 Nov  8  2016 custom_get_by_id.sql
-rw-r--r-- 1 ts3 staff  131 Nov  8  2016 custom_insert.sql
-rw-r--r-- 1 ts3 staff  70K Nov  8  2016 defaults.sql
-rw-r--r-- 1 ts3 staff  158 Nov  8  2016 group_delete.sql
-rw-r--r-- 1 ts3 staff   69 Nov  8  2016 group_id_get_by_name.sql
-rw-r--r-- 1 ts3 staff   74 Nov  8  2016 group_insert_bulk_snapshot_get_mapping.sql
-rw-r--r-- 1 ts3 staff  169 Nov  8  2016 group_insert_bulk_snapshot.sql
-rw-r--r-- 1 ts3 staff   81 Nov  8  2016 group_insert.sql
-rw-r--r-- 1 ts3 staff   75 Nov  8  2016 group_member_delete_by_groupid.sql
-rw-r--r-- 1 ts3 staff  107 Nov  8  2016 group_member_delete.sql
-rw-r--r-- 1 ts3 staff  120 Nov  8  2016 group_member_detail_get_by_groupid.sql
-rw-r--r-- 1 ts3 staff  110 Nov  8  2016 group_member_get.sql
-rw-r--r-- 1 ts3 staff  152 Nov  8  2016 group_member_insert_bulk.sql
-rw-r--r-- 1 ts3 staff   99 Nov  8  2016 group_member_insert.sql
-rw-r--r-- 1 ts3 staff   49 Nov  8  2016 group_members_get_by_groupid.sql
-rw-r--r-- 1 ts3 staff   72 Nov  8  2016 group_members_get_by_id.sql
-rw-r--r-- 1 ts3 staff   51 Nov  8  2016 group_members_get_by_serverid.sql
-rw-r--r-- 1 ts3 staff   57 Nov  8  2016 group_rename.sql
-rw-r--r-- 1 ts3 staff   51 Nov  8  2016 groups_get_by_serverid.sql
-rw-r--r-- 1 ts3 staff   69 Nov  8  2016 groups_get_by_serverid_type.sql
-rw-r--r-- 1 ts3 staff   21 Nov  8  2016 groups_get.sql
-rw-r--r-- 1 ts3 staff   39 Nov  8  2016 info_delete.sql
-rw-r--r-- 1 ts3 staff   68 Nov  8  2016 info_get_by_ident.sql
-rw-r--r-- 1 ts3 staff   58 Nov  8  2016 info_insert.sql
-rw-r--r-- 1 ts3 staff  131 Nov  8  2016 message_delete.sql
-rw-r--r-- 1 ts3 staff  133 Nov  8  2016 message_get_by_clientid.sql
-rw-r--r-- 1 ts3 staff  117 Nov  8  2016 message_get_unread_by_clientid.sql
-rw-r--r-- 1 ts3 staff  305 Nov  8  2016 message_insert.sql
-rw-r--r-- 1 ts3 staff  103 Nov  8  2016 message_list_by_clientid.sql
-rw-r--r-- 1 ts3 staff  161 Nov  8  2016 message_update_flag.sql
-rw-r--r-- 1 ts3 staff 2,3K Nov  8  2016 perm_copy_default_permissions.sql
-rw-r--r-- 1 ts3 staff   65 Nov  8  2016 perm_delete_by_groupid.sql
-rw-r--r-- 1 ts3 staff  105 Nov  8  2016 perm_delete_by_permid.sql
-rw-r--r-- 1 ts3 staff  896 Nov  8  2016 perm_delete_by_serverid.sql
-rw-r--r-- 1 ts3 staff   39 Nov  8  2016 perm_get_by_id.sql
-rw-r--r-- 1 ts3 staff   52 Nov  8  2016 perm_get_by_serverid.sql
-rw-r--r-- 1 ts3 staff  151 Nov  8  2016 perm_group_copy.sql
-rw-r--r-- 1 ts3 staff  389 Nov  8  2016 perm_group_get_mapping.sql
-rw-r--r-- 1 ts3 staff  440 Nov  8  2016 perm_group_perm_copy.sql
-rw-r--r-- 1 ts3 staff  278 Nov  8  2016 perm_insert_bulk.sql
-rw-r--r-- 1 ts3 staff  176 Nov  8  2016 perm_insert.sql
-rw-r--r-- 1 ts3 staff  927 Nov  8  2016 permission_load_channel_group_total.sql
-rw-r--r-- 1 ts3 staff  399 Nov  8  2016 permission_load_other.sql
-rw-r--r-- 1 ts3 staff 1,9K Nov  8  2016 permission_load_server_and_channel_group_total.sql
-rw-r--r-- 1 ts3 staff  925 Nov  8  2016 permission_load_server_group_total.sql
-rw-r--r-- 1 ts3 staff  433 Nov  8  2016 perm_rename.sql
-rw-r--r-- 1 ts3 staff   93 Nov  8  2016 perm_update_get_groups.sql
-rw-r--r-- 1 ts3 staff   41 Nov  8  2016 properties_delete_by_id.sql
-rw-r--r-- 1 ts3 staff   55 Nov  8  2016 properties_delete_by_string_id.sql
-rw-r--r-- 1 ts3 staff  152 Nov  8  2016 properties_insert_by_id.sql
-rw-r--r-- 1 ts3 staff  183 Nov  8  2016 properties_insert_by_string_id.sql
-rw-r--r-- 1 ts3 staff   42 Nov  8  2016 properties_list_by_id.sql
-rw-r--r-- 1 ts3 staff   56 Nov  8  2016 properties_list_by_string_id.sql
-rw-r--r-- 1 ts3 staff  104 Nov  8  2016 server_clear_traffic_stats.sql
-rw-r--r-- 1 ts3 staff  188 Nov  8  2016 server_delete_get_qa_clients.sql
-rw-r--r-- 1 ts3 staff 1,3K Nov  8  2016 server_delete.sql
-rw-r--r-- 1 ts3 staff   52 Nov  8  2016 server_get_byid.sql
-rw-r--r-- 1 ts3 staff   56 Nov  8  2016 server_get_byport.sql
-rw-r--r-- 1 ts3 staff  140 Nov  8  2016 server_insert.sql
-rw-r--r-- 1 ts3 staff   67 Nov  8  2016 server_list_by_machine_id.sql
-rw-r--r-- 1 ts3 staff   22 Nov  8  2016 server_list.sql
-rw-r--r-- 1 ts3 staff 1,1K Nov  8  2016 server_snapshot_delete_failed.sql
-rw-r--r-- 1 ts3 staff 1,1K Nov  8  2016 server_snapshot_delete.sql
-rw-r--r-- 1 ts3 staff   85 Nov  8  2016 server_update_autostart.sql
-rw-r--r-- 1 ts3 staff   87 Nov  8  2016 server_update_machine_id.sql
-rw-r--r-- 1 ts3 staff   75 Nov  8  2016 server_update_port.sql
-rw-r--r-- 1 ts3 staff  276 Nov  8  2016 server_update_traffic_stats.sql
-rw-r--r-- 1 ts3 staff   72 Nov  8  2016 token_delete_by_key.sql
-rw-r--r-- 1 ts3 staff   74 Nov  8  2016 token_get_by_key.sql
-rw-r--r-- 1 ts3 staff  340 Nov  8  2016 token_insert.sql
-rw-r--r-- 1 ts3 staff   48 Nov  8  2016 token_list.sql
-rw-r--r-- 1 ts3 staff  541 Nov  8  2016 update_12.sql
-rw-r--r-- 1 ts3 staff 3,4K Nov  8  2016 update_13.sql
-rw-r--r-- 1 ts3 staff  402 Nov  8  2016 update_14.sql
-rw-r--r-- 1 ts3 staff   73 Nov  8  2016 update_15.sql
-rw-r--r-- 1 ts3 staff  197 Nov  8  2016 update_16.sql
-rw-r--r-- 1 ts3 staff  158 Nov  8  2016 update_17.sql
-rw-r--r-- 1 ts3 staff   57 Nov  8  2016 update_18.sql
-rw-r--r-- 1 ts3 staff   26 Nov  8  2016 update_19.sql
-rw-r--r-- 1 ts3 staff   61 Nov  8  2016 update_20.sql
-rw-r--r-- 1 ts3 staff   51 Nov  8  2016 update_21.sql
-rw-r--r-- 1 ts3 staff   64 Nov  8  2016 update_22.sql
-rw-r--r-- 1 ts3 staff   92 Nov  8  2016 update_23.sql
-rw-r--r-- 1 ts3 staff  209 Nov  8  2016 update_24.sql
-rw-r--r-- 1 ts3 staff  312 Nov  8  2016 update_25.sql
-rw-r--r-- 1 ts3 staff   26 Nov  8  2016 update_26.sql
-rw-r--r-- 1 ts3 staff   93 Nov  8  2016 update_database_version.sql
-rw-r--r-- 1 ts3 staff  121 Nov  8  2016 update_mariadb_26.sql
-rw-r--r-- 1 ts3 staff  979 Nov  8  2016 update_permissions_12.sql
drwxr-sr-x 2 ts3 staff 4,0K Nov  8  2016 updates_and_fixes

/usr/local/ts3/teamspeak3-server_linux_amd64/sql/create_sqlite
insgesamt 32K
drwxr-sr-x 2 ts3 staff 4,0K Nov  8  2016 .
drwxr-sr-x 5 ts3 staff  12K Nov  8  2016 ..
-rw-r--r-- 1 ts3 staff 9,0K Nov  8  2016 create_tables.sql
-rw-r--r-- 1 ts3 staff 1,1K Nov  8  2016 drop_tables.sql

/usr/local/ts3/teamspeak3-server_linux_amd64/sql/updates_and_fixes
insgesamt 28K
drwxr-sr-x 2 ts3 staff 4,0K Nov  8  2016 .
drwxr-sr-x 5 ts3 staff  12K Nov  8  2016 ..
-rw-r--r-- 1 ts3 staff 3,7K Nov  8  2016 convert_mysql_to_mariadb.sql
-rw-r--r-- 1 ts3 staff 5,1K Nov  8  2016 mariadb_fix_latin_utf8.sql

/usr/local/ts3/teamspeak3-server_linux_amd64/sql/create_mariadb
insgesamt 32K
drwxr-sr-x 2 ts3 staff 4,0K Nov  8  2016 .
drwxr-sr-x 5 ts3 staff  12K Nov  8  2016 ..
-rw-r--r-- 1 ts3 staff 9,3K Nov  8  2016 create_tables.sql
-rw-r--r-- 1 ts3 staff  840 Nov  8  2016 drop_tables.sql

/usr/local/ts3/teamspeak3-server_linux_amd64/tsdns
insgesamt 944K
drwxr-sr-x 2 ts3 staff 4,0K Nov  8  2016 .
drwxr-sr-x 9 ts3 staff 4,0K Aug 31 12:25 ..
-rw-r--r-- 1 ts3 staff 3,4K Nov  8  2016 README
-rwxr-xr-x 1 ts3 staff 921K Nov  8  2016 tsdnsserver
-rw-r--r-- 1 ts3 staff 2,8K Nov  8  2016 tsdns_settings.ini.sample
-rw-r--r-- 1 ts3 staff 2,8K Nov  8  2016 USAGE

**Comment by penderes** [comment]
Further info from running the script with --debug:

Regarding the "stack underflow":
+++ getLatestStableTS3ServerVersion
++++ wget -t 1 -T 3 https://www.teamspeak.com/versions/server.json -q -O -
++++ jshon -e linux -e x86_64 -e version
++++ tr -d '"'
warning: nothing to read
internal error: stack underflow

Regarding the tar/bzip error:
TeamSpeak 3 server instance stopped for update process.
++ findRealTS3RootDirectory /usr/local/ts3/teamspeak3-server_linux_amd64
++ [[ -d /opt/exagear/ ]]
++ TEAMSPEAK_ROOT_DIRECTORY=/usr/local/ts3/teamspeak3-server_linux_amd64/
++ echo -n /usr/local/ts3/teamspeak3-server_linux_amd64/
++ echo -n /usr/local/ts3/teamspeak3-server_linux_amd64/
++ md5sum
++ cut -d ' ' -f 1
++ rsync -a --no-inc-recursive --exclude files /usr/local/ts3/teamspeak3-server_linux_amd64/ /tmp/TS3Tools/TS3UpdateScript/7119af29c3412149379cf2e77b426886
++ rsync -a --no-inc-recursive --exclude files /usr/local/ts3/teamspeak3-server_linux_amd64/ /var/backups/TS3Tools/TS3UpdateScript/7119af29c3412149379cf2e77b426886
Backup created successful.
++ findRealTS3RootDirectory /usr/local/ts3/teamspeak3-server_linux_amd64
++ [[ -d /opt/exagear/ ]]
++ TEAMSPEAK_ROOT_DIRECTORY=/usr/local/ts3/teamspeak3-server_linux_amd64/
++ echo -n /usr/local/ts3/teamspeak3-server_linux_amd64/
++ sed 's/\/$//'
++ echo
++ grep -Eo '^[0-9\.?]+'
++ echo -n /usr/local/ts3/teamspeak3-server_linux_amd64
++ md5sum
++ cut -d ' ' -f 1
++ grep /usr/local/ts3/teamspeak3-server_linux_amd64 TS3InstanceInfos.txt
++ echo 'OK|/usr/local/ts3/teamspeak3-server_linux_amd64|3.0.13.6|Unknown|Linux|/usr/local/ts3/teamspeak3-server_linux_amd64/logs/|amd64|ts3|1000|staff||||SQLite'
++ cut -d '|' -f 1
++ echo 'OK|/usr/local/ts3/teamspeak3-server_linux_amd64|3.0.13.6|Unknown|Linux|/usr/local/ts3/teamspeak3-server_linux_amd64/logs/|amd64|ts3|1000|staff||||SQLite'
++ cut -d '|' -f 2
++ echo 'OK|/usr/local/ts3/teamspeak3-server_linux_amd64|3.0.13.6|Unknown|Linux|/usr/local/ts3/teamspeak3-server_linux_amd64/logs/|amd64|ts3|1000|staff||||SQLite'
++ cut -d '|' -f 3
++ echo 'OK|/usr/local/ts3/teamspeak3-server_linux_amd64|3.0.13.6|Unknown|Linux|/usr/local/ts3/teamspeak3-server_linux_amd64/logs/|amd64|ts3|1000|staff||||SQLite'
++ cut -d '|' -f 4
++ echo 'OK|/usr/local/ts3/teamspeak3-server_linux_amd64|3.0.13.6|Unknown|Linux|/usr/local/ts3/teamspeak3-server_linux_amd64/logs/|amd64|ts3|1000|staff||||SQLite'
++ tr '[:upper:]' '[:lower:]'
++ cut -d '|' -f 5
++ echo 'OK|/usr/local/ts3/teamspeak3-server_linux_amd64|3.0.13.6|Unknown|Linux|/usr/local/ts3/teamspeak3-server_linux_amd64/logs/|amd64|ts3|1000|staff||||SQLite'
++ cut -d '|' -f 6
++ echo 'OK|/usr/local/ts3/teamspeak3-server_linux_amd64|3.0.13.6|Unknown|Linux|/usr/local/ts3/teamspeak3-server_linux_amd64/logs/|amd64|ts3|1000|staff||||SQLite'
++ cut -d '|' -f 7
++ echo 'OK|/usr/local/ts3/teamspeak3-server_linux_amd64|3.0.13.6|Unknown|Linux|/usr/local/ts3/teamspeak3-server_linux_amd64/logs/|amd64|ts3|1000|staff||||SQLite'
++ cut -d '|' -f 8
++ echo 'OK|/usr/local/ts3/teamspeak3-server_linux_amd64|3.0.13.6|Unknown|Linux|/usr/local/ts3/teamspeak3-server_linux_amd64/logs/|amd64|ts3|1000|staff||||SQLite'
++ cut -d '|' -f 9
++ echo 'OK|/usr/local/ts3/teamspeak3-server_linux_amd64|3.0.13.6|Unknown|Linux|/usr/local/ts3/teamspeak3-server_linux_amd64/logs/|amd64|ts3|1000|staff||||SQLite'
++ cut -d '|' -f 10
++ echo 'OK|/usr/local/ts3/teamspeak3-server_linux_amd64|3.0.13.6|Unknown|Linux|/usr/local/ts3/teamspeak3-server_linux_amd64/logs/|amd64|ts3|1000|staff||||SQLite'
++ cut -d '|' -f 11
++ echo 'OK|/usr/local/ts3/teamspeak3-server_linux_amd64|3.0.13.6|Unknown|Linux|/usr/local/ts3/teamspeak3-server_linux_amd64/logs/|amd64|ts3|1000|staff||||SQLite'
++ cut -d '|' -f 12
++ echo 'OK|/usr/local/ts3/teamspeak3-server_linux_amd64|3.0.13.6|Unknown|Linux|/usr/local/ts3/teamspeak3-server_linux_amd64/logs/|amd64|ts3|1000|staff||||SQLite'
++ cut -d '|' -f 13
++ echo 'OK|/usr/local/ts3/teamspeak3-server_linux_amd64|3.0.13.6|Unknown|Linux|/usr/local/ts3/teamspeak3-server_linux_amd64/logs/|amd64|ts3|1000|staff||||SQLite'
++ cut -d '|' -f 14
tar: Das sieht nicht wie ein „tar“-Archiv aus.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cp: der Aufruf von stat für „teamspeak3-server_linux-amd64/*“ ist nicht möglich: Datei oder Verzeichnis nicht gefunden
Could not update TeamSpeak 3 server instance. Do you have enough space on '/usr/local/ts3/teamspeak3-server_linux_amd64'?
./TS3UpdateScript: Zeile 2128: expect: Kommando nicht gefunden.
Due of the failed update, the TS3UpdateScript has created a debug report in /usr/local/ts3/teamspeak3-server_linux_amd64/20170831-1256-ts3us-debug-report.md

**Comment by penderes** [comment]
Fixed the problem:
I dug a bit deeper into the script and found the command where the problem occured:

`wget -t 1 -T 3 https://www.teamspeak.com/versions/server.json -q -O | jshon -e linux -e x86_64 -e version
`

When running this without the -q parameter, I can see the following error:
> ERROR: The certificate of 'www.teamspeak.com' is not trusted.

This was easily fixed by running `apt-get install ca-certficates`.

Now everything works flawlessly. I have a vServer and run a Debian minimal installation. So it might be worth taking this up in the documentation that certificates need to be present, because you're using https to connect to teamspeak.com/etc. This is just not directly obvious due to the -q parameter.

**Comment by Sebi94nbg** [comment]
Hey,
great, that you were able to solve this issue by your own.

Yeah, I'll add it to the requirements / documentation. Thanks for the hint!

**Comment by Sebi94nbg** [comment]
Updated requirements. Will be included in the next version.
