### ISSUE TITLE
BUG - Server Version 3.2.0

### ISSUE THREAD

**Issue by ruymb** [TS3Tools/TS3UpdateScript#77]
The new update from 3.1.3 - 3.2.0 is not working with this script I have tried on 3 of my teamspeak servers and all are coming up with the same issue. Here is the log from the update script please fix.

Trying to backup temporary server passwords. Please wait...
Could not backup temporary server passwords. Don't worry. You may just don't had any.
TeamSpeak 3 server instance stopped for update process.
Backup created successful.
tar: This does not look like a tar archive

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cp: cannot stat 'teamspeak3-server_linux-amd64/*': No such file or directory
Could not update TeamSpeak 3 server instance. Do you have enough space on '/home/teamspeak/teamspeak3-server_linux_amd64'?
Due of the failed update, the TS3UpdateScript has created a debug report in /home/teamspeak/teamspeak3-server_linux_amd64/20180515-1206-ts3us-debug-report.md
Update failed. Rollback to the version '3.1.3'.
TeamSpeak 3 server instance was started successful.
Backup was deleted successful.

Cleaning up...

Summary of measured execution time for each step
Total script: 64s
Self-Test: 4s
Collecting Information: 1s
Validation: 0s
Execution Mechanism: 59s
Backuping temporary server passwords: 10s
Formatting temporary server passwords for restore: 0s
Collecting information for poke mechanism and poking all online clients: 20s
Poking all online clients: 0s
Cleanup: 0s

Thanks for using this script! Support the development of this script and donate: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7ZRXLSC2UBVWE

**Comment by Sebi94nbg** [comment]
Thanks for reporting this issue, @ruymb!

I've updated the code and removed old code, which shouldn't be necessary anymore, because everyone should use at least a server version 3.1.x. :)

Please update your script and try it again: `./TS3UpdateScript --update-script`

It should work now. :)

**Comment by ruymb** [comment]
All is working accordingly now, I would recommend you add this to your documentation to let people know that it will now support only 3.1+

**Comment by Sebi94nbg** [comment]
Yeah, I‘ll update it. :)

Thanks for your feedback!

**Comment by Sebi94nbg** [comment]
Added it to [Readme: Requirements](https://github.com/TS3Tools/TS3UpdateScript#requirements).
