### ISSUE TITLE
TS3Updatescript doesn´t work.

### ISSUE THREAD

**Issue by Betalinx** [TS3Tools/TS3UpdateScript#80]
Hello, i want to update my teamspeak server from 3.0.13.7 to 3.2.0 but it doesn´t work.

I followed the steps of this link : https://github.com/TS3Tools/TS3UpdateScript/issues/79.
But the script want to update to 3.2.0...

If i accept that happens following with this :  

Script Version: 5.6.4 (2018-05-10)
Script License: Community (No support bought)
Support License: Community (No support plan bought)

Donate and support this script: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7ZRXLSC2UBVWE

------------------------------------------------------------------

Please wait... Script is working...

Performing self-tests as preventive measures against possible failures                                                                             [ OK ]

Please update this script to the latest version by using the following command: ./TS3UpdateScript --update-script

Collecting necessary information for further tasks                                                                                                 [ OK ]

All collected information were validated successfully as preventive measures against possible failures                                             [ INFO ]

1 TeamSpeak 3 server instance found...

Collecting as much as possible information for following TeamSpeak 3 server instance: /home/teamspeak3/teamspeak3-server_linux_amd64
1 instance for update process...
############################################################################
        Do you want to update this instance to the following version? 3.2.0

        Installation Directory: /home/teamspeak3/teamspeak3-server_linux_amd64
        Installed Version: 3.0.13.7 (Build: 1498547480)
        Installed Platform: Linux
        Installed Architecture: amd64

        Instance Log Files: /home/teamspeak3/teamspeak3-server_linux_amd64/logs/
        Instance TSDNS Binary: /home/teamspeak3/teamspeak3-server_linux_amd64/tsdns/tsdnsserver
        TSDNS Status: Inactive

        Owner: teamspeak3 (UID: 1000)
        Group: teamspeak3 (GID: 1000)

        ServerQuery IP: 127.0.0.1
        ServerQuery Port: 10011

        Database Type: SQLite
############################################################################
Please answer: ([y]es/[n]o) y
Trying to backup temporary server passwords. Please wait...
Could not backup temporary server passwords. Don't worry. You may just don't had any.
TeamSpeak 3 server instance stopped for update process.
Backup created successful.
tar: This does not look like a tar archive

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cp: cannot stat 'teamspeak3-server_linux-amd64/*': No such file or directory
Could not update TeamSpeak 3 server instance. Do you have enough space on '/home/teamspeak3/teamspeak3-server_linux_amd64'?

Due of the failed update, the TS3UpdateScript has created a debug report in /home/teamspeak3/teamspeak3-server_linux_amd64/20180708-2147-ts3us-debug-report.md
Update failed. Rollback to the version '3.0.13.7'.
TeamSpeak 3 server instance was started successful.
Backup was deleted successful.

Cleaning up...

Summary of measured execution time for each step
Total script: 51s
Self-Test: 5s
Collecting Information: 1s
Validation: 0s
Execution Mechanism: 45s
Backuping temporary server passwords: 20s
Formatting temporary server passwords for restore: 0s
Cleanup: 0s

Debug report:

# TS3tools TS3UpdateScript Debug Report

Date and time of report: 20180708-2147
TS3UpdateScript Installation Path: /root/TS3UpdateScript-5.6.4
TS3UpdateScript Version: 5.6.4
TS3UpdateScript Parameters: --check

## TS3UpdateScript output

Please copy and paste the output of the shell below this line and/or attach a debug file of this script.

## Operating System Details

Distributor ID: Debian
Description:    Debian GNU/Linux 8.11 (jessie)
Release:        8.11
Codename:       jessie

Linux *** 2.6.32-042stab127.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64 GNU/Linux

### root User locale

LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

### teamspeak3 User locale

LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

## TS3 Update Details

Update path: 3.0.13.7 -> 3.2.0
Instance path: /home/teamspeak3/teamspeak3-server_linux_amd64

**Comment by Sebi94nbg** [comment]
Hey,
You tried to update from 3.0.x to 3.2.0. You need to update from 3.0.x to 3.1.x and then to 3.2.x.

Please follow the exact steps described here: https://github.com/TS3Tools/TS3UpdateScript/issues/79#issuecomment-400984324

**Comment by Betalinx** [comment]
Yes, i did this step as described above.

**Comment by Sebi94nbg** [comment]
Your output above shows something different:

`Installed Version: 3.0.13.7 (Build: 1498547480)`

`Do you want to update this instance to the following version? 3.2.0`

You need to update to version 3.1.x first. Then to 3.2.x.

`./TS3UpdateScript --check --set-release`

**Comment by Betalinx** [comment]
No. I know that as described above... so i followed the steps by #79 but it want to update to 3.2.0 and not to 3.1.x ...

**Comment by Sebi94nbg** [comment]
Yeah, that's the problem. You need to use the option / parameter `--set-release` in order to update to the version, which you've set in the `configs/config.all`.

`./TS3UpdateScript --check --set-release`

**Comment by Betalinx** [comment]
So now the server doesn´t run anymore ...

#Output

Please wait... Script is working...

Performing self-tests as preventive measures against possible failures                                                    [ OK ]

Please update this script to the latest version by using the following command: ./TS3UpdateScript --update-script

Collecting necessary information for further tasks                                                                        [ OK ]

All collected information were validated successfully as preventive measures against possible failures                    [ INFO ]

1 TeamSpeak 3 server instance found...

Collecting as much as possible information for following TeamSpeak 3 server instance: /home/teamspeak3/teamspeak3-server_linux_amd64
1 instance for update process...
############################################################################
        Do you want to update this instance to the following version? 3.1.3

        Installation Directory: /home/teamspeak3/teamspeak3-server_linux_amd64
        Installed Version: 3.0.13.7 (Build: 1498547480)
        Installed Platform: Linux
        Installed Architecture: amd64

        Instance Log Files: /home/teamspeak3/teamspeak3-server_linux_amd64/logs/
        Instance TSDNS Binary: /home/teamspeak3/teamspeak3-server_linux_amd64/tsdns/tsdnsserver
        TSDNS Status: Inactive

        Owner: teamspeak3 (UID: 1000)
        Group: teamspeak3 (GID: 1000)

        ServerQuery IP: 127.0.0.1
        ServerQuery Port: 10011

        Database Type: SQLite
############################################################################
Please answer: ([y]es/[n]o) y
Trying to backup temporary server passwords. Please wait...
Could not backup temporary server passwords. Don't worry. You may just don't had any.
TeamSpeak 3 server instance stopped for update process.
Backup created successful.
TeamSpeak 3 server instance was updated successful.
TeamSpeak 3 server instance was started successful.
Waiting 15 seconds to execute TeamSpeak 3 server and TSDNS health check...
TeamSpeak 3 server instance is still running.
Backup was deleted successful.

Cleaning up...

Summary of measured execution time for each step
Total script: 49s
Self-Test: 4s
Collecting Information: 0s
Validation: 1s
Execution Mechanism: 44s
Backuping temporary server passwords: 20s
Formatting temporary server passwords for restore: 0s
Cleanup: 0s

**Comment by Sebi94nbg** [comment]
Your server is still running:
> Waiting 15 seconds to execute TeamSpeak 3 server and TSDNS health check...
> TeamSpeak 3 server instance is still running.
You may be unable to connect as it's installing database updates. Just check your instance log file (_0.log). :)

**Comment by Betalinx** [comment]
My license is not working anymore (Non Profit).  Why the license isn´t working anymore?

2018-07-08 20:36:12.809068|INFO    |ServerLibPriv |   |TeamSpeak 3 Server 3.1.3 (2018-04-27 20:24:32)
2018-07-08 20:36:12.809218|INFO    |ServerLibPriv |   |SystemInformation: Linux 2.6.32-042stab127.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64 Binary:$
2018-07-08 20:36:12.809247|WARNING |ServerLibPriv |   |The system locale is set to "C" this can cause unexpected behavior. We advice you to repair yo$
2018-07-08 20:36:12.809938|INFO    |DatabaseQuery |   |dbPlugin name:    SQLite3 plugin, Version 3, (c)TeamSpeak Systems GmbH
2018-07-08 20:36:12.809967|INFO    |DatabaseQuery |   |dbPlugin version: 3.11.1
2018-07-08 20:36:12.810203|INFO    |DatabaseQuery |   |checking database integrity (may take a while)
2018-07-08 20:36:12.838587|WARNING |Accounting    |   |Unable to open licensekey.dat, falling back to limited functionality
2018-07-08 20:36:12.838783|INFO    |Accounting    |   |Licensing Information
2018-07-08 20:36:12.838809|INFO    |Accounting    |   |licensed to       : *******
2018-07-08 20:36:12.838829|INFO    |Accounting    |   |type              : No License
2018-07-08 20:36:12.838879|INFO    |Accounting    |   |starting date     : Wed May 31 22:00:00 2017
2018-07-08 20:36:12.838899|INFO    |Accounting    |   |ending date       : Fri Aug 31 22:00:00 2018
2018-07-08 20:36:12.838915|INFO    |Accounting    |   |max virtualservers: 1
2018-07-08 20:36:12.838931|INFO    |Accounting    |   |max slots         : 32
2018-07-08 20:36:13.700001|INFO    |              |   |Puzzle precompute time: 805
2018-07-08 20:36:13.700385|INFO    |FileManager   |   |listening on 0.0.0.0:30033
2018-07-08 20:36:13.724350|ERROR   |VirtualSvrMgr |   |loading VirtualServer(1) failed to start, error: max slot limit reached
2018-07-08 20:36:13.724633|INFO    |CIDRManager   |   |updated query_ip_whitelist ips: 127.0.0.1/32,
2018-07-08 20:36:13.724901|INFO    |Query         |   |listening on 0.0.0.0:10011

**Comment by Sebi94nbg** [comment]
Maybe due of this?

> 2018-07-08 20:36:12.809247|WARNING |ServerLibPriv | |The system locale is set to "C" this can cause unexpected behavior. We advice you to repair yo$

Also see: https://github.com/TS3Tools/TS3UpdateScript/blob/master/docs/BEST_PRACTICES_ANALYZER.md#the-system-locale-is-set-to-c-this-can-cause-unexpected-behavior-teamspeak-advices-you-to-repair-your-locale

It detects the license, but it says "No License" although it returns the valid dates.

**Comment by Betalinx** [comment]
#  File generated by update-locale

this is the only text in  /etc/default/locale.

**Comment by Betalinx** [comment]
Now the log is empty.

**Comment by Sebi94nbg** [comment]
I recommend to update the server to the latest version, download the license again and replace it on your TeamSpeak 3 server. This might fix the issue. Please note, that you need to restart your TeamSpeak 3 server after you've replaced the license file.

If not, you should fix the locale issue.

**Comment by Betalinx** [comment]
Hm i fixed this, i changed the max_slots to 32. Now i try to update with the new script to 3.2.0 and start the server if this work i try to request a new license.

**Comment by Betalinx** [comment]
I can not launch the server as teamspeak user.. only as root.

**Comment by Betalinx** [comment]
Now it works fine. Thank you.

**Comment by Sebi94nbg** [comment]
Thanks for your feedback!

Did you figure out, what the issue with your license was? Did you just download a new license file?
