### ISSUE TITLE
Update to Teamspeak Server 3.3.0 not possible

### ISSUE THREAD

**Issue by boehseronkel** [TS3Tools/TS3UpdateScript#81]
Teamspeak Server 3.3.0 was released yesterday and i tried to update my Server with the Update Script.
The Script itself runs fine, but then gives me the Message that my Server (v. 3.2.0) is up to date already.

**Comment by Sebi94nbg** [comment]
Hi @boehseronkel ,
the latest stable release is still 3.2.0 as you can see on their [download page](https://teamspeak.com/en/downloads#server). The stable version is detected by reading the official version JSON-file: https://www.teamspeak.com/versions/server.json (currently also 3.2.0).

TeamSpeak Server version 3.3.0 is currently only available as Beta, so you need to add the parameter `--beta-release` to your TS3UpdateScript update command. The script is fetching the latest beta version from the official download server here: http://dl.4players.de/ts/releases/pre_releases/server/?C=M;O=D

To update your TeamSpeak server to the latest stable version `3.2.0`, you need to run this command:
`./TS3UpdateScript --check [additional parameters]`

If you want to update your TeamSpeak server to the latest beta version 3.3.0 (Beta 3 right now), you need to run this command:
`./TS3UpdateScript --check --beta-release [additional parameters]`

**Comment by boehseronkel** [comment]
According to the Teamspeak Forums the Version 3.3.0 was released as stable yesterday, but maybe they just need some days to implement the new version to their official download page.

Thank you for the information and the great TS Update Script 👍

**Comment by Sebi94nbg** [comment]
Yeah, updating the new files and version strings takes usually some time as they don't do this by themself.

No problem. :)
