### ISSUE TITLE
Script sagt server gestoppt - server läuft jedoch

### ISSUE THREAD

**Issue by skapytek** [TS3Tools/TS3UpdateScript#82]
Hallo,
wenn ich das script ausführe bekomme ich folgende meldung:
Folgende Instanz benoetigt ein Update, ist jedoch gestoppt und wird nicht vom Skript angefasst: /home/xxxxxx/xxxxx (Installierte Version: 3.1.0)

Server läuft jedoch und ist online.
Woher stammt dieser fehler bzw. wie kann ich ihn fixen?

lg

**Comment by Sebi94nbg** [comment]
Hallo,
stelle bitte sicher, dass das `ts3server_startscript.sh` einem normalen Benutzer als Eigentümer zugeordnet ist und NICHT root.

Danach stelle bitte sicher, dass der Eigentümer dieses Benutzers den Server gestartet hat und der Prozess entsprechend unter dem Benutzer läuft.

Normalerweise legt man einen dedizierten Linux Benutzer wie z.B. "teamspeak" an und gibt diesem alle Rechte auf den TS3 Server Ordner: `chown teamspeak -R /home/xxxxxx/xxxxx/`

**Comment by skapytek** [comment]
Hallo,
Benutzer ist nicht root.
Benutzer lautet "zapXXXX"

lg

**Comment by Sebi94nbg** [comment]
Ok und als welcher Benutzer läuft der TeamSpeak 3 Server momentan?

`ps aux | grep -i ts3`

**Comment by skapytek** [comment]
zap354626_v2 lautet der benutzer

**Comment by Sebi94nbg** [comment]
Kannst du bitte folgende Ausgaben zeigen?

`ps aux | grep -i ts3`

`ls -lha /home/xxxxxx/xxxxx/`

Ich kann dir sonst nicht helfen. Das Skript selbst funktioniert einwandfrei - ich habe es mehrfach in den letzten Tagen benutzt und andere Kunden ebenfalls.

**Comment by skapytek** [comment]
zap3546+  4695  0.0  0.0  26196  1376 ?        Ss   Aug08   0:01 SCREEN -AmdL -S zap354626_v2 bash -c sh ts3server_minimal_runscript.sh default_voice_port=9987 query_port=10011 filetransfer_port=30033 loginname=serveradmin serveradmin_password= inifile=ts3server.ini
zap3546+  4697  0.0  0.0   4292    76 pts/2    Ss+  Aug08   0:00 sh ts3server_minimal_runscript.sh default_voice_port=9987 query_port=10011 filetransfer_port=30033 loginname=serveradmin serveradmin_password= inifile=ts3server.ini
zap3546+  4700  0.3  0.9 1275584 19308 pts/2   Sl+  Aug08  14:07 ./ts3server default_voice_port=9987 query_port=10011 filetransfer_port=30033 loginname=serveradmin serveradmin_password= inifile=ts3server.ini
root     25250  0.0  0.0  11116   900 pts/3    S+   13:29   0:00 grep -i ts3


drwxrwx--- 9 zap354626_v2 zap354626    4.0K Aug  8 21:34 .
drwxr-xr-x 3 zap354626_v2 zap354626_v2 4.0K Aug  8 12:46 ..
-rwxrwx--- 1 zap354626_v2 zap354626     220 May 15  2017 .bash_logout
-rwxrwx--- 1 zap354626_v2 zap354626    3.5K May 15  2017 .bashrc
-rwxrwx--- 1 zap354626_v2 zap354626     675 May 15  2017 .profile
-rwxrwx--- 1 zap354626_v2 zap354626      19 Aug  8 21:34 .ts3server_license_accepted
-rwxrwx--- 1 zap354626_v2 zap354626     55K May  8 08:13 CHANGELOG
-rwxrwx--- 1 zap354626_v2 zap354626     67K May  8 08:13 LICENSE
drwxrwx--- 3 zap354626_v2 zap354626    4.0K Feb 13 11:47 doc
drwxrwx--- 4 zap354626_v2 zap354626    4.0K Aug  8 12:46 files
-rwxrwx--- 1 zap354626_v2 zap354626    978K May  8 08:13 libts3db_mariadb.so
-rwxrwx--- 1 zap354626_v2 zap354626    2.1M May  8 08:13 libts3db_sqlite3.so
drwxrwx--- 2 zap354626_v2 zap354626    4.0K Aug  8 21:35 logs
-rwxrwx--- 1 zap354626_v2 zap354626       0 Aug  8 12:46 query_ip_blacklist.txt
-rwxrwx--- 1 zap354626_v2 zap354626      51 Aug  8 20:15 query_ip_whitelist.txt
drwxrwx--- 2 zap354626_v2 zap354626    4.0K Aug  8 21:30 redist
drwxrwx--- 2 zap354626_v2 zap354626    4.0K Aug  8 21:30 serverquerydocs
drwxrwx--- 5 zap354626_v2 zap354626     12K Aug  8 21:31 sql
-rwxrwx--- 1 zap354626_v2 zap354626     11M May  8 08:13 ts3server
-rwxrwx--- 1 zap354626_v2 zap354626     484 Aug  8 21:34 ts3server.ini
-rwxrwx--- 1 zap354626_v2 zap354626     484 Aug  8 21:34 ts3server.inie
-rwxrwx--- 1 zap354626_v2 zap354626    431K Aug 11 18:19 ts3server.sqlitedb
-rwxrwx--- 1 zap354626_v2 zap354626_v2  32K Aug 12 13:31 ts3server.sqlitedb-shm
-rwxrwx--- 1 zap354626_v2 zap354626_v2 1.0M Aug 12 13:31 ts3server.sqlitedb-wal
-rwxrwx--- 1 zap354626_v2 zap354626     129 May  8 08:13 ts3server_minimal_runscript.sh
-rwxrwx--- 1 zap354626_v2 zap354626    2.6K May  8 08:13 ts3server_startscript.sh
drwxrwx--- 2 zap354626_v2 zap354626    4.0K Aug  8 21:31 tsdns

**Comment by Sebi94nbg** [comment]
Das erklärt das Problem natürlich. Du hast den Server auf eine Art und Weise gestartet, wie man es nicht macht. Deshalb kommt das Skript damit nicht klar.

Bitte stoppe deinen TS3 Server wie du es gewöhnlich tust oder beende einfach alle Prozesse:
```
kill 4695
kill 4697
kill 4700
```

Danach starte ihn bitte richtig. Das `ts3server_minimal_runscript.sh` Skript wird ausschließlich für die initiale Installation verwendet - also einmal. Danach nie wieder.

Logge dich zu erst als der entsprechende Benutzer ein:
`su - zap354626_v2`

Und starte den TS3 Server über das dafür vorgesehene Skript `ts3server_startscript.sh` und nicht über die Binary und/oder per `screen`:
`./ts3server_startscript.sh start inifile=ts3server.ini`

Du kannst den Teil `inifile=ts3server.ini` auch in die `ts3server_startscript.sh` Datei reinschreiben, damit du es nicht immer wieder mit angeben musst.

Vorher: `COMMANDLINE_PARAMETERS="${2}" #add any command line parameters you want to pass here`
Nachher: `COMMANDLINE_PARAMETERS="${2} inifile=ts3server.ini" #add any command line parameters you want to pass here`

Dann lautet der Befehl wie folgt:
`./ts3server_startscript.sh start`

**Comment by skapytek** [comment]
Danke läuft nun!

**Comment by Sebi94nbg** [comment]
Läuft! Kein Problem.
