### ISSUE TITLE
Script sagt server gestoppt - server läuft jedoch

### ISSUE THREAD

**Issue by skapytek** [TS3Tools/TS3UpdateScript#83]
Hallo,
wenn ich das script ausführe bekomme ich folgende meldung:
Folgende Instanz benoetigt ein Update, ist jedoch gestoppt und wird nicht vom Skript angefasst: /home/xxxxxx/xxxxx (Installierte Version: 3.1.0)

Server läuft jedoch und ist online.
Woher stammt dieser fehler bzw. wie kann ich ihn fixen?
Benutzer ist nicht root.
Benutzer lautet "zapXXXX"

lg

**Comment by Sebi94nbg** [comment]
Bitte nicht immer ein neues Thema öffnen. Hier geht's weiter: #82
