### ISSUE TITLE
Script does nothing

### ISSUE THREAD

**Issue by mfnalex** [TS3Tools/TS3UpdateScript#87]
While the script used to work, it does nothing now. The script always hangs at this message:

"Versuche temporaere Server Passwoerter zu backupen. Bitte warten...
Konnte temporaere Server Passwoerter nicht backupen. Keine Sorge. Du hattest vielleicht einfach keine."

After that, nothing happens.

**Comment by mfnalex** [comment]
After a while, this is shown:

"TeamSpeak 3 Server Instanz wurde fuer den Update Prozess gestoppt.
Backup erfolgreich erstellt.
cp: reguläre Datei './ts3server' kann nicht angelegt werden: Das Programm kann nicht ausgeführt oder verändert werden (busy)
Konnte die TeamSpeak 3 Server Instanz nicht aktualisieren. Hast du genug freien Speicherplatz? '/home/ts3'?
Aufgrund des fehlgeschlagenen Updates, hat das TS3UpdateScript einen Debug Report erstellt: /home/ts3/20180822-1106-ts3us-debug-report.md
Update fehlgeschlagen. Rollback zur alten Version '3.2.0'.
Konnte die TeamSpeak 3 Server Instanz nicht starten.
Das Backup fuer diese Instanz wurde nicht geloescht. Das Backup findest du hier: /tmp/TS3Tools/TS3UpdateScript/216c87c984bddec1a15c3151df8036f2/

Raeume auf...

Zusammenfassung von gemessenen Zeiten fuer einzelne Schritte
Skript insgesamt: 414s
Selbst-Tests: 4s
Informationen sammeln: 4s
Validierung: 0s
Ausfuehrungsmechanismus: 406s
Sichern von temporaeren Server Passwoertern: 40s
Formatierung von temporaeren Server Passwoertern fuer den Restore: 0s
Aufraeumen: 0s
"

**Comment by mfnalex** [comment]
I sent you an email with the logfile, because I didn't know if there are passwords or other important information visible in the log.

**Comment by Sebi94nbg** [comment]
Thanks, I've received it. I'll check it and come back to you as soon as I have any news. :)

The only critical information in this log is usually the ServerQuery serveradmin password and this is censored by the script. All other information like IP address(es), ports and Linux system information (eg. Kernel + OS Name and Version) + TeamSpeak server version are not confidential.

**Comment by Sebi94nbg** [comment]
The debug report looks fine so far. There seems to be an issue with your TS3 server instance processes. Some files needs to be changed, but are locked by the usage of processes. I had a similar issue a long time ago. The solution was following:

_Hint: Dear reader, the following commands are based on the provided debug report - you may need to change them a little bit (eg. the Linux user at point 2)._

1. Rebooted Linux server to make sure, all processes are fine and not hanging / busy anymore. You can filter out all necessary processes and kill them manually, but this takes more time than a quick reboot. ;)
2. Logged in as dedicated Linux TeamSpeak user: `su - ts3`
3. Optionally deleted old TeamSpeak server logs: `rm logs/*`
4. Started TeamSpeak: `./ts3server_startscript.sh start`
5. Deleted old files from the TS3UpdateScript, which were not deleted due of a unexpected stop of the script: `rm CLIENTLIST.txt COLLECTING_INFORMATION_STATUS.txt IGNORE_CLIENTLIST.txt POKELIST.txt POKELIST_UNSORTED.txt SELF_TEST_STATUS.txt SERVERLIST.txt TS3InstanceInfos.txt TS3InstancePaths.txt .ts3updatescript.lock VALIDATION_STATUS.txt TS3UpdateScript/COLLECTING_INFORMATION_STATUS.txt TS3UpdateScript/SELF_TEST_STATUS.txt TS3UpdateScript/SERVERLIST.txt TS3UpdateScript/TS3InstanceInfos.txt TS3UpdateScript/TS3InstancePaths.txt TS3UpdateScript/VALIDATION_STATUS.txt`
6. Moved the TS3UpdateScript outside of the root folder of the TeamSpeak 3 server: `mv /home/ts3/TS3UpdateScript/ /root/` (I usually install it always in the root's home folder or in a sub directory of the TeamSpeak users home directory, but outside of the TeamSpeak server installation)

You also could move the TeamSpeak 3 server to a sub folder:
_Attention: Stop the TeamSpeak server before!_
```
# Execute as "ts3" user
mkdir teamspeak
mv /home/ts3/* /home/ts3/teamspeak/
mv /home/ts3/teamspeak/TS3UpdateScript/ /home/ts3/
```
7. Execute the TS3UpdateScript as root user and try the update again: `./TS3UpdateScript --check`

If you end up with the same result at the end, I need to debug this directly on your server. I can provide you my SSH key, that I can check this in a quiet minute (rather hour :D) by my own or we do some screen sharing together. It's up to you. :)

**Comment by mfnalex** [comment]
Unfortunately, this did not change anything. I will send you an e-mail later this day or tomorrow and would be very happy if we could find the root of the problem :)

**Comment by Sebi94nbg** [comment]
Hey @mfnalex, do you still need help here or can I close this issue? :)

**Comment by mfnalex** [comment]
Sorry, I forgot to answer. The Problem was a systemd service that restarted the server automatically. Issue can be closed :)
