### ISSUE TITLE
Cannot execute /bin/dummy

### ISSUE THREAD

**Issue by Dilski** [TS3Tools/TS3UpdateScript#9]
Creating Backup of existing TeamSpeak 3 server             
Your server will be updated right now                 
Importing SQLite database                        
Importing Query IP white- and blacklist                 
Adjusting ownership and group of files            
Adding COMMANDLINE_PARAMETERS 'inifile=ts3server.ini' to ts3server_startscript.sh              
Cannot execute /bin/dummy
Rollback to the version '3.0.7.1', because the server could not start                     
Cannot execute /bin/dummy
Your new server version could not start. Deployed backup of version '3.0.7.1'                          
Cleaning up system                    
Finish!

**Comment by Sebi94nbg** [comment]
Hello,

        Cannot execute /bin/dummy
I can't help you, if don't tell me the name of the binary.

Please activate the debugging function as following:
1) Edit TS3UpdateScript.sh
2) Uncomment line with 'set -x'
3) Save file

Now execute the script again and redirect any output to a debug-file. For example like this:
      ./TS3UpdateScript.sh --check --delete-old-logs --inform-online-clients &> debug.txt

Attach or show me the content of the debug.txt.

**Comment by Sebi94nbg** [comment]
Not interested for a solution?
