### ISSUE TITLE
instance needs an update, but is stopped an not touched by the script

### ISSUE THREAD

**Issue by boyfromgermany** [TS3Tools/TS3UpdateScript#91]
Is it Broken or am i doing it wrong ? 
it runs the script but it wont update the server 
Please wait... Script is working...

Performing self-tests as preventive measures against possible failures                                                              [ OK ]

Collecting necessary information for further tasks                                                                                  [ OK ]

All collected information were validated successfully as preventive measures against possible failures                              [ INFO ]

1 TeamSpeak 3 server instance found...

Collecting as much as possible information for following TeamSpeak 3 server instance: /usr/local/bin/teamspeak3-server_linux_amd64/files/channel_15/teamspeak3-server_linux_amd64
1 instance for update process...

Following instance needs an update, but is stopped and not touched by the script: /usr/local/bin/teamspeak3-server_linux_amd64/files/channel_15/teamspeak3-server_linux_amd64 (Installed Version: /usr/local/bin/teamspeak3-server_linux_amd64/files/channel_15/teamspeak3-server_linux_amd64/logs/ts3server_2017-11-16__20_36_07.043227_0.log)

Cleaning up...

Summary of measured execution time for each step
Total script: 6s
Self-Test: 4s
Collecting Information: 2s
Validation: 0s
Execution Mechanism: 0s
Cleanup: 0s

**Comment by Sebi94nbg** [comment]
Hey @boyfromgermany,
The script is working fine. :)

Please take a look at issue #90, comment [418308617](https://github.com/TS3Tools/TS3UpdateScript/issues/90#issuecomment-418308617) to solve this issue.

**Comment by Sebi94nbg** [comment]
I'll close this issue due to long inactivity. Please feel free, to comment / re-create this issue.
