### ISSUE TITLE
compatability with systemd

### ISSUE THREAD

**Issue by mfnalex** [TS3Tools/TS3UpdateScript#96]
I am using systemd to launch TS3. However, that way, the script cannot stop the server as it always restarts.
When I stop the server using systemd and then run the script, it says it cannot update the server because it was stopped.

```
[Unit]
Description=TeamSpeak 3 Server
 
[Service]
ExecStart=/home/ts3/ts3server_startscript.sh start
ExecStop=/home/ts3/ts3server_startscript.sh stop
PIDFile=/home/ts3/ts3server.pid
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=teamspeak
User=ts3
Group=ts3
Type=forking
[Install]
WantedBy=multi-user.target
```

**Comment by mfnalex** [comment]
I could use systemd to stop the server, then start the minimal startscript and then the script, however that would result in at least three server restarts and I try to keep the downtime as short as possible. So I was wondering if there is a better solution :)

**Comment by Sebi94nbg** [comment]
This has nothing todo with the TS3UpdateScript. The issue tracker is only for the TS3UpdateScript, not for all TeamSpeak related topics.

However: Systemd is the correct and best way to handle this.

This is how our systemd file looks like: `/etc/systemd/system/ts3server.service`
```
[Unit]
Description=TeamSpeak 3 Server
After=network.target mysqld.service
ConditionPathExists=!/home/teamspeak/.ts3updatescript.lock

[Service]
User=teamspeak
Group=teamspeak
WorkingDirectory=/home/teamspeak/
ExecStart=/home/teamspeak/ts3server_startscript.sh start
ExecStop=/home/teamspeak/ts3server_startscript.sh stop
ExecReload=/home/teamspeak/ts3server_startscript.sh restart
PIDFile=/home/teamspeak/ts3server.pid
Restart=always
RestartSec=5
Type=forking

[Install]
WantedBy=multi-user.target
Alias=ts3server.service
```

I think, you only miss the `WorkingDirectory` variable in yours.

**Comment by mfnalex** [comment]
Ah, the important line was this:

```
ConditionPathExists=!/home/teamspeak/.ts3updatescript.lock
```
