### ISSUE TITLE
Genutzter Downloadlink

### ISSUE THREAD

**Issue by Assassins88** [TS3Tools/TS3UpdateScript#98]
Warum nutzt das Script 4players zum laden der neuen Version und nicht

https://files.teamspeak-services.com/releases/server/

???

Auf 4players ist nicht immer gleich die aktuellste Version verfügbar. Die aktuelle Version 3.8.0 zum Beispiel fehlt da noch auf den Servern. Auf den Downloadservern von TeamSpeak selbst ist sie verfügbar.

**Comment by Sebi94nbg** [comment]
Die Änderung ist derzeit in Bearbeitung. Siehe #97.

Früher - vor der Version 3.8.0 - gab es diesen Mirror / Download Server nicht. Zu dieser Zeit hat TeamSpeak die Dateien bei anderen Hostern verwaltet.

Ich warte aktuell noch auf Feedback von TeamSpeak, ob die neuen Versionen weiterhin bei http://dl.4players.de und http://teamspeak.gameserver.gamed.de hochgeladen werden oder nicht. Je nach Feedback bleiben die beiden Mirrors drin oder werden entfernt.
