### ISSUE TITLE
Update Error v3.8.0 - parse error: type 'object' has no elements to extract (arg 8)

### ISSUE THREAD

**Issue by P4nz3rwels** [TS3Tools/TS3UpdateScript#99]
I get on every update 3 times the parse error: type 'object' has no elements to extract (arg 8) after backuping the old version.

here is my debug of the updating.

[debug.txt](https://github.com/TS3Tools/TS3UpdateScript/files/3256628/debug.txt)

------------------------------------------------------------------

Please wait... Script is working...

Fuehre Selbst-Tests als Preventivmassnahme gegen moegliche Fehler durch                                                                    [ OK ]

Sammel notwendige Informationen fuer weitere Aufgaben                                                                                      [ OK ]

Alle gesammelten Informationen wurden erfolgreich als Praeventivmassnahme gegen moegliche Fehler validiert.                                [ INFO ]

1 TeamSpeak 3 Server Instanz gefunden...

Sammel so viele wie moegliche Informationen fuer folgende TeamSpeak 3 Server Instanz: /usr/local/teamspeak3/teamspeak3-server_linux_amd64
1 Instanz fuer den Update Prozess...
############################################################################
        Moechtest du diese Instanz auf die folgende Version aktualisieren? 3.8.0

        Installationsverzeichnis: /usr/local/teamspeak3/teamspeak3-server_linux_amd64
        Installierte Version: 3.7.1 (Build: 1553759186)
        Installierte Plattform: Linux
        Installierte Architektur: amd64

        Instanz Log Dateien: /usr/local/teamspeak3/teamspeak3-server_linux_amd64/logs/
        Instanz TSDNS Binary: /usr/local/teamspeak3/teamspeak3-server_linux_amd64/tsdns/tsdnsserver
        TSDNS Status: Inaktiv

        Eigentuemer: teamspeak3 (UID: 1001)
        Gruppe: teamspeak3 (GID: 1000)

        ServerQuery IP: 127.0.0.1
        ServerQuery Port: 10011

        Datenbank Typ: SQLite
############################################################################
Bitte antworten: ([y]es/[n]o) y
Versuche temporaere Server Passwoerter zu backupen. Bitte warten...
Konnte temporaere Server Passwoerter nicht backupen. Keine Sorge. Du hattest vielleicht einfach keine.
TeamSpeak 3 Server Instanz wurde fuer den Update Prozess gestoppt.
Backup erfolgreich erstellt.
parse error: type 'object' has no elements to extract (arg 8)
parse error: type 'object' has no elements to extract (arg 8)
parse error: type 'object' has no elements to extract (arg 8)
TeamSpeak 3 Server Instanz wurde erfolgreich aktualisiert.
TeamSpeak 3 Server Instanz wurde erfolgreich gestartet.
Warte 15 Sekunden, um den TeamSpeak 3 Server und TSDNS Health Check durchzufuehren...
Die TeamSpeak 3 Server Instanz laeuft nicht mehr.
Aufgrund des fehlgeschlagenen Updates, hat das TS3UpdateScript einen Debug Report erstellt: /usr/local/teamspeak3/teamspeak3-server_linux_amd64/20190605-1206-ts3us-debug-report.md
Update fehlgeschlagen. Rollback zur alten Version '3.7.1'.
TeamSpeak 3 Server Instanz wurde erfolgreich gestartet.
Backup wurde erfolgreich geloescht.

Raeume auf...

Zusammenfassung von gemessenen Zeiten fuer einzelne Schritte
Skript insgesamt: 87s
Selbst-Tests: 5s
Informationen sammeln: 3s
Validierung: 0s
Ausfuehrungsmechanismus: 78s
Sichern von temporaeren Server Passwoertern: 40s
Formatierung von temporaeren Server Passwoertern fuer den Restore: 0s
Aufraeumen: 1s

**Comment by Sebi94nbg** [comment]
Thanks for reporting this issue!

This is a known issue. I'm currently waiting for feedback from TeamSpeak, if they will still upload upcoming / new releases / versions to the previous known files servers or only to their own new one.

Just wrote TeamSpeak a few seconds ago again as they wanted to provide me feedback by yesterday.

This parse error does NOT effect the update and / or cause any issues / errors. It's only complaining, that it can not parse a JSON file, because some entries are missing.

Also see #97:
> I'm currently waiting for feedback from TeamSpeak, if they will still upload new versions to the previous known mirrors http://dl.4players.de and http://teamspeak.gameserver.gamed.de or not.
> 
> Depending on the feedback, those mirrors get fully removed or will remain in the code.

I'll leave your issue open, that other people can read this as well, before they create a new issue. :)

**Comment by Sebi94nbg** [comment]
TeamSpeak answered:
> I just spoke to the head of development and he said the old ones will not be updated anymore
> So all updates and new versions will only be through: https://files.teamspeak-services.com

Source (facebook private chat message):
![image](https://user-images.githubusercontent.com/5154682/58981169-24b16c00-87d2-11e9-8b30-8a62036a7d1d.png)

Based on this feedback, I'll remove the previous known mirrors.

**Comment by Sebi94nbg** [comment]
Change and fix has been released with [TS3UpdateScript v5.7.0](https://github.com/TS3Tools/TS3UpdateScript/releases/tag/5.7.0). :)
